### ISSUE TITLE
gokart-pre checksum mismatch

### ISSUE THREAD

**Issue by ferki** [MichaelMure/git-bug#1018]
Since `gokart-pre` became a dependency on #974, I can't install cleanly from current default branch due to an error along the lines of:

```
go: downloading github.com/selesy/gokart-pre v0.5.2-rc1
verifying github.com/selesy/gokart-pre@v0.5.2-rc1/go.mod: checksum mismatch
        downloaded: h1:cYSoG9HL7P1T9mKLcc1zs1+ZItJ8ZGmc+JmnOPg2hX8=
        go.sum:     h1:a2Ej7TE206x7KjQr2kud7nckfVFQaIv7ljzT1KxFdVg=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

`gokart-pre` appears to be a patched version of `gokart`, and I'm not sure how to verify the authenticity of version 0.5.2-rc1 in a safe manner.

I'm happy to provide further details if needed. I might be able to send a PR as well, but I need guidance on how to determine the correct hash.

**Comment by arnaudlecam** [comment]
Same issue for me...

**Comment by ferki** [comment]
Thanks for the fix, @MichaelMure! I confirm I can install git-bug again from the git repo :rocket:
