### ISSUE TITLE
comment edition with the command line

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#108]
Comment needs to be editable from the command line.

This warrant a new command: `git bug comment edit <id>`

Comment's id can be retrieved using `git bug comment`

**Comment by sladyn98** [comment]
This is a feature that is required since it is already present in the TermUI.
I will try and send in a PR for this issue :+1:

**Comment by sladyn98** [comment]
@MichaelMure one more thing we would need to take care of would be comment identities.We cannot allow edits to users to whom the comment does not belong.

**Comment by MichaelMure** [comment]
Yes, but to do that properly, we will need cryptography and signature, as well as a ACL system. I don't want to add a "soft" constraint for now (only allow the author to edit), because that would make the current version forward incompatible once more than the author can edit (on github, repo admin can edit a comment as an example).

**Comment by sladyn98** [comment]
But in the case when the exporter is developed this system becomes paramount. For now we could allow edits to comments by any author. And in the last case you mentioned we would have to first determine the repo admin to allow him the edit... beacuse if not we wouldn't be able to export the bug.

**Comment by MichaelMure** [comment]
This has been working for long
