### ISSUE TITLE
Jira Bridge: Project doesn't exist

### ISSUE THREAD

**Issue by litetex** [MichaelMure/git-bug#1123]
I tried to create a jira bridge with the following command line:
```
git bug bridge configure --name=jira --target=jira --base-url=https://DOMAIN.atlassian.net --project=PROJECT --login=MY_EMAIL --token=TOKEN
```
however the output is ``Error: Project TEST doesn't exist on https://DOMAIN.atlassian.net, or authentication credentials for (MY_EMAIL) are invalid``.

I'm pretty sure that I entered everything correctly:
* The domain exists and is valid
* The project exists and is valid and can be retrieved from the https://DOMAIN.atlassian.net/rest/api/2/project/PROJECT endpoint
* The login+token is correct

Is there a debug option which could tell me what is going wrong? (http request and reponse would help)
Otherwise there is likely a bug somewhere or something is missing in the documentation.

**Comment by sudoforge** [comment]
@litetex can you provide a little more information about this?

specifically:

- is this still reproducible for you?
- what version of git-bug are you using? `git bug version`

**Comment by litetex** [comment]
Sry but I currently can't provide any further details as I opened this a year ago and I'm no longer using git-bug.

**Comment by sudoforge** [comment]
@litetex not a problem! thanks for letting me know.
