### ISSUE TITLE
git-bug maintenance status

### ISSUE THREAD

**Issue by sudoforge** [MichaelMure/git-bug#1157]
@MichaelMure, it's been two years since the last commit, which is roughly ~200 commits ahead of the last release. Many issues, pull requests, and even a high severity CVE have gone unanswered.

Are you still planning on maintaining this project? I ask because I would be happy to help step in, and potentially take over. I am of a singular mindset that this is the best approach to issue management, and would like to ensure that the community has an active project that has bugs, security issues, and feature requests addressed.

If you are not able to support this project at this time, and are not interested in keeping it alive, can it be archived, to avoid confusion with users? There's absolutely no issue with this route, of course; life gets busy, and this is the fate of many open source projects.

**Comment by MichaelMure** [comment]
Two years, jeez ....

Life is busy indeed. I'm still convinced that there is value in git-bug in many ways, and I'd like that project to continue growing.

You'll find an invite to become a member of this repo. I suppose an immediate task would be to upgrade some dependencies and cut a release if the current master is in shape. I'll let you judge though.

Let me know if you need anything, and thank you.

**Comment by sudoforge** [comment]
Sounds good to me! I've accepted the invitation; thanks for sending that out so quickly.

> I'm still convinced that there is value in git-bugin many ways, and I'd  like that project to continue growing.

I absolutely agree. I love the git-native approach to bug management, and quite frankly, if you had decided to archive this, I would have started building out an alternative. I don't want to use an issue tracker that isn't embedded in my repo :)

**Comment by sudoforge** [comment]
I'll bring things up-to-date, and take a look at cutting a release soon.
