### ISSUE TITLE
cache: memory management

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#132]
Currently, with an import from scratch by the github importer on a 700 issues real world repo, all stored in memory leads to a 67MB memory usage, so It's really premature at this point, but it will be necessary eventually.

Here is what we can do:
- [ ] implement a [LRU policy](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)) or equivalent, with a configurable maximum number of entities kept in memory
- optionally, allow for an importer to explicitly not store the newly created issues in the cache. This could be done by either an explicit API, or by setting the LRU limit very low.

**Comment by bhavukkalra** [comment]
hello @MichaelMure could i take up this issue?
I would love to implement a least recently used cache for git-bug for proper memory utlisation

**Comment by bhavukkalra** [comment]
also could i get some tips on how to proceed with this...
A heads up would be really great..
