### ISSUE TITLE
WebUI - allow to create bugs

### ISSUE THREAD

**Issue by hoijui** [MichaelMure/git-bug#158]
If iI did not miss anything, the Web-UI is currently read-only.
To be ablle to create bugs, comments, edit, remove and so on in a way that works for any kind of (non-technical) users, is very important for any project that might has such users.

An alternative solution coudl be, to make an alreayd existing GUI/WebUI to use git-bug as a backend, like suggeste for example in https://github.com/MichaelMure/git-bug/issues/80.

What are your thoughs about this, how hard would it be to implement it, what problems do you see?

**Comment by hoijui** [comment]
Somewhat related comment in an older issue: https://github.com/MichaelMure/git-bug/issues/31#issuecomment-415910526

**Comment by MichaelMure** [comment]
That's correct, the web UI is only read only for now, just because no one took care of that yet. It's an important task, not only for local rich editing (images, files ...), but also to eventually create a public portal which will accept external users.

Note that most of the GraphQL mutations already exist, so that's almost purely an JS/web job.

**Comment by hoijui** [comment]
I am not a web dev, and .. generally have little to no idea about the technologies you used in hte web UI.
Can you recommend something.. an IDE/editor or tutorial or something to get started?

**Comment by MichaelMure** [comment]
There is plenty of tutorial floating around if you search for `react graphql apollo`. I don't have anything specific to recommend. But I'm not gonna lie, that's a lot to ingest.

**Comment by MichaelMure** [comment]
@cheshirekow seems to be working on this :heart: : https://github.com/cheshirekow/git-bug/tree/cheshirekow-webui

**Comment by cheshirekow** [comment]
As @MichaelMure mentioned, I created an [add-bug][2] screen. It seems to work but I think there is something I need to do in order to "update the apollo cache". I have no idea what that means but I read it in one of the tutorials I was following. The result is that the bug-list is out of date when you go back it it. I just hit refresh for now. I filed a bug to fix it :wink:.

![add_bug](https://user-images.githubusercontent.com/1309820/67509544-21673180-f648-11e9-9ce7-cacb657d2265.gif)

In any case, I'm just tinkering around so if someone else wants to dedicate some real time to this please don't think I've claimed it or anything. I doubt I'll have much time to dedicate to it but I'd love to dig in a little more if I can. 

@hoijui I also am a complete n00b to react, graphql, and even JSX but I found it pretty easy to get started (I have some javascript experience though). The instructions at [webui/Readme.md][1] worked just fine and I just used a plain editor (vscode) to make my change. Feel free to take a look at [my branch][2] and diff it against the upstream to see how I implemented the feature.  

[1]: https://github.com/MichaelMure/git-bug/blob/master/webui/Readme.md
[2]: https://github.com/cheshirekow/git-bug/tree/cheshirekow-webui

**Comment by hoijui** [comment]
cool!
thank you @cheshirekow ! will do next time get the courage for it.

**Comment by MichaelMure** [comment]
This is actively worked on by @sandhose and @ludovicm67 :tada:

**Comment by claudioantonio** [comment]
Hi @MichaelMure , @cheshirekow and @hoijui .
Any news about this feature? I'm interested to help. ;-)

**Comment by MichaelMure** [comment]
@claudioantonio no one is working on this at the moment, so feel free to take a stab at it! Much appreciated.

**Comment by claudioantonio** [comment]
Ok @MichaelMure . I'll take a look at the [work started](https://github.com/cheshirekow/git-bug/tree/cheshirekow-webui) by @cheshirekow .

**Comment by claudioantonio** [comment]
@MichaelMure to start the backend is cygwin sufficient to exec the makefile?

**Comment by MichaelMure** [comment]
@claudioantonio as you likely won't change the graphQL API, you can use your regular git-bug binary. No need for cygwin or anything, just the classic web dev tools like `npm`.
There is a dedicated Readme to explain the process (again, you don't even have to compile git-bug yourself here): https://github.com/MichaelMure/git-bug/blob/master/webui/Readme.md

**Comment by MichaelMure** [comment]
As you will see, adding a comment already works, but there is plenty of features missing compared to the CLI. Pick what itch you the most ;)

**Comment by claudioantonio** [comment]
Does the image below represent a good enough solution?

The changes will be:
1. Filter label added - left aligned
2. Filter input text aligned to the left
3. Green "New issue" button added aligned to the right like github UI for issues feature

![gitbug suggestion](https://user-images.githubusercontent.com/12503122/105617063-f1628d00-5dba-11eb-8729-f45297fb9fac.png)

**Comment by MichaelMure** [comment]
That's neat :)

**Comment by claudioantonio** [comment]
Hi @MichaelMure !
I´m studying about GraphQL and Apollo to be able to finish issue creation.
I´m trying to use Insomnia (app similar to Postman) to make a simple GraphQL query but the answer is always an error message. 😠 

Insomnia can fetch git-bug schema (so connection to server is fine) and I used the autocomplete feature to write the query (so no misspelling) but I did not get a successful response yet as shown in the image below. Is this query correct?

Insomnia also generates a curl version of my request and the error result is the same... 😭  Any idea to bring me some light would be great!

**Curl version**
curl --request GET \
  --url http://127.0.0.1:3001/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"{\n  repository {\n    allBugs {\n      totalCount\n    }\n  }\n}"}'

**Query in Insomnia**
![image](https://user-images.githubusercontent.com/12503122/106064539-cdfc5280-60d8-11eb-92f3-ccd4cdd746c0.png)

**Comment by claudioantonio** [comment]
Hi @MichaelMure !
I read about GraphQL and I did the Apollo tutorial. I had no previous experience with GraphQL before.
I´m already able to create new bugs from the git-bug API using Insomnia (an app like Postman). See image below.
![image](https://user-images.githubusercontent.com/12503122/106135055-27e73180-6146-11eb-9308-308cf8beeed7.png)

However, I´m having problems to execute the same GraphQL mutation command by React/Apollo. The code should be simple. I will print what i´m doing and I will be glad If You or any other collaborator can give me any hint, ok?

**GQL**
`
const NEW_BUG = gql`
  mutation newBugMutation($input: NewBugInput!) {
    newBug(input: $input) {
      bug {
        title
        message
      }
    }
  }
`;
`
**React Page**
`
function NewPage() {
  const classes = useStyles({ searching: false });
  let inputField: any;
  const [newBug, { data }] = useMutation(NEW_BUG);

  function submitNewIssue(e: FormEvent) {
    e.preventDefault();
    newBug({
      variables: {
        input: {
          title: inputField.value,
          message: 'Message',
        },
      },
    });
    inputField.value = '';
  }
[...]
`

**Comment by MichaelMure** [comment]
Sure, but react is not really my area of expertise.

If that helps, git-bug also has a built-in GraphQL playground when you start the webui: `http://127.0.0.1:44159/playground`

**Comment by claudioantonio** [comment]
Hi @MichaelMure !
Wow! I liked the playground a lot. ;-)

Sorry for the lack of the error message in the last comment.
![image](https://user-images.githubusercontent.com/12503122/106139473-3d5f5a00-614c-11eb-8080-e36f0904760c.png)

**Comment by MichaelMure** [comment]
That looks like a [HTTP error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422), maybe looking at the network debugger in your browser would help?

**Comment by claudioantonio** [comment]
Problem solved @MichaelMure !

It was a little bit frustrating that a code generator make it work automagically adding just one file but... 
c'est la vie.. 😃 Probably was something related to return object type conversion.
I will improve the Readme file with the lessons learned during this issue to give quick context for graphql begginer´s, like me.

Can You edit this issue title to "WebUI - Allow to create bugs"?
I would like to create a new issue specifically for edition as "WebUI - Allow to change a bug title". Today It is already possible to add comments for existing issues. 😉

**Comment by MichaelMure** [comment]
Done. Feel free to open more issues for the other parts (or straight up a PR :-D)

**Comment by claudioantonio** [comment]
@MichaelMure what considerations about permissions should I consider?
Who can create or edit a bug?
I found a component that checks if the user is logged in to decide if comments can be added or not. About what kind of login are talking about? 🤔

**Comment by MichaelMure** [comment]
@claudioantonio sorry I missed that one.

At the moment, anyone can create and edit any bugs (including comments they are not the author of). This should change in the future once the identity system become smarter. For now, maybe it's best to match whatever is possible in git-bug core?

Regarding the authentication, there is three different scenario:
- the user might might not have an identity yet (that is, `Repository.userIdentity` *can* be nil in GraphQL). In that case we want to have a read-only UI if we don't have a user yet.
- in the future, the webUI might be used for a public portal (possibly with external auth like github OAuth where identities would be imported in git-bug at first login). Again, we want a read-only view when we don't have a user logged in yet.
- the webUI can be started with `--read-only` to force a read-only view.

**Comment by MichaelMure** [comment]
So in the react code, the write-enabled part of the UI are guarded with the `IfLoggedIn` component.

**Comment by claudioantonio** [comment]
@MichaelMure I think this issue can be closed. ;-)

**Comment by claudioantonio** [comment]
@MichaelMure I will create a issue to handle specifically this permission question. ;-)
