### ISSUE TITLE
bridge: importing events occurred after a known date

### ISSUE THREAD

**Issue by A-Hilaly** [MichaelMure/git-bug#167]
For now the importer can only iterate over all available issues/comments/events and import them if they don't exist locally . 

We can add two flags to the bridge `pull` and `push` subcommands in order to allow only importing and exporting new events:
##### 1 - `--no-resume` 

for example, by default the importer will have to import only new events. passing this flag will force the bridge to import all available issues and events.

**example:** `git bug bridge pull --no-resume`

##### 2 - `--since`
to import/export events after a known date
**example:** `git bug bridge push --since=2019-06-08T21:49:06Z`

**Comment by MichaelMure** [comment]
Possibly, we would also need a `--since`-like flag that understand the Lamport time.

Also, the importer/exporter should probably be smart enough to resume where it left off on it's own.
