### ISSUE TITLE
feat: graceful kill for the bridge export and import functionalities

### ISSUE THREAD

**Issue by A-Hilaly** [MichaelMure/git-bug#175]
for now interrupting git-bug while exporting or importing issues can damage local or remote and cause problems if when we re-execute these commands.
To avoid this we can implement a global context to gracefully shutdown these functions ! for this we need:

- [ ] To use a global context for the bridge importer and exporter
- [ ] use the context to cancel http requests
- [ ] Add cancel functions to Interrupt handler
- [ ] Commit operations before exiting the functions (SetMetadataOperation in the exporter for example `)

(this bug was created using the new exporter)

**Comment by MichaelMure** [comment]
> (this bug was created using the new exporter)

:tada: :tada: :tada: :tada: :tada: :tada: :tada: 

great work !
