### ISSUE TITLE
Gitlab importation - unhandled note type

### ISSUE THREAD

**Issue by cgivord** [MichaelMure/git-bug#185]
When trying to import issues from Gitlab, it starts and then:

```
panic: unhandled note type

goroutine 1 [running]:
github.com/MichaelMure/git-bug/bridge/gitlab.(*gitlabImporter).ensureNote(0xc420290080, 0xc4201edfc0, 0xc4201a8aa0, 0xc42058a180, 0x0, 0x0)
```

It still successfully imported some bugs. :)

The failing bug may be titled with some accents, quotes and parentheses, I don't know if this could be the cause of the crash.

**Comment by MichaelMure** [comment]
Hey, thanks for giving it a try :)

Could you give us the repo URL ?

**Comment by cgivord** [comment]
Sadly I can't, as this is a private repo.

However, the title and the body contains quotes (singles and doubles) and that could be something to investigate.

**Comment by cgivord** [comment]
It gives me a noteType = 10 (NOTE_ASSIGNED)

I guess it would be a nice addition to handle assigned and unassigned types of notes ! :)

**Comment by A-Hilaly** [comment]
Hey thanks for the feed back ! i literally wrote everything to handle these cases and forgot to use them in the importer ... sending a fix PR ASAP

**Comment by cgivord** [comment]
Thanks to all of you for the quick replies and the fix.

Keep up the good work ! Awesome project !! :+1:

**Comment by MichaelMure** [comment]
You're welcome. Thanks for the feedback, it helps pushing forward :)
