### ISSUE TITLE
Is push access required?

### ISSUE THREAD

**Issue by sio** [MichaelMure/git-bug#188]
I didn't find it mentioned in the documentation, but if I understand correctly, any user wishing to open a new issue or to comment on existing one must have push access to the repository. Is that correct? Are there any workarounds to allow untrusted users to participate?

Thank you!

**Comment by MichaelMure** [comment]
As of now, that's correct. Of course it would be super useful to be able to edition from people without push access. The plan is to make the webui into a portal that can be exposed on the public internet, and accept various auth system (github oauth, ...). But someone would need to help building the webui. The graphql API is here but there is work to do on the frontend.

**Comment by sio** [comment]
Thank you :-)
