### ISSUE TITLE
Add more integrations with bug trackers

### ISSUE THREAD

**Issue by ligurio** [MichaelMure/git-bug#191]
`git-bug` has importers from Github, GitLab and Launchpad.
It would be nice to have importers for bug trackers used in commercial development: like Jira, TFS and Youtrack. I know it can be a pain to support many bugtrackers API's. Probably `bugwarrior` code can be reused - https://github.com/ralphbean/bugwarrior, as it is already supports many bugtrackers.

**Comment by MichaelMure** [comment]
`bugwarrior` being in python, we can't practically use it directly. That said, we can certainly have a look and gain some insights or tricks. @A-Hilaly, have a look :)

Thanks for briging that up, i didn't know it existed. The UI of taskwarrior is especially interesting, there is many things we could do better in the CLI tools.

**Comment by A-Hilaly** [comment]
Awesome ! I didn't know about bugwarrior and taskwarrior before, they seem like very cool projects. We can definitely gain some insights from them  :+1:

**Comment by MichaelMure** [comment]
Closing this one in favor of individual tasks for each bugtracker as we can't use bugwarrior directly.

**Comment by jahagirdar** [comment]
What is the exact issue with using bugwarrior?
I am a regular user of taskwarrior and recently shifted to git-bug from bugseverywhere, I would love to be able to import bugs in taskwarrior and manage them along with other tasks...
