### ISSUE TITLE
bug: github bridge iterator panic when capacity is set to 1

### ISSUE THREAD

**Issue by A-Hilaly** [MichaelMure/git-bug#197]
The GitHub bridge iterator actually panics with "index out of range" when it capacity is set to 1. With a capacity different than one, the iterator continue functions properly.
This doesn't affect the master branch because the capacity is set to 10

**Comment by MichaelMure** [comment]
This is probably not relevant anymore now that the github bridge has been reworked (thanks @rng-dynamics !). We can re-open if it's still an issue.
