### ISSUE TITLE
feat: support cleaner cancellation or replacement in util/interrupt

### ISSUE THREAD

**Issue by A-Hilaly** [MichaelMure/git-bug#209]
Instead of storing cleaners in an array we can use maps the help identify and cancel/replace them in the other parts of git-bug code. See https://github.com/MichaelMure/git-bug/blob/master/util/interrupt/cleaner.go#L13

**Comment by MichaelMure** [comment]
Be careful, cleaners should be executed in the reverse order that they have been defined, in a similar fashion as defer in go.

**Comment by A-Hilaly** [comment]
Good point, i didn't see that cleaner are appended in reverse order https://github.com/MichaelMure/git-bug/blob/master/util/interrupt/cleaner.go#L19
