### ISSUE TITLE
feat: filtering and ordering in the bug list

### ISSUE THREAD

**Issue by kseistrup** [MichaelMure/git-bug#21]
It would be nice – and make it easier to get an overview of what needs to be done – to be able to hide closed issues when doing a `git bug ls`.

**Comment by MichaelMure** [comment]
In a more general sense, git-bug needs filtering and ordering in the bug list.

For performance, that also means having a sort of cache serialized on disk with a subset of values for each bug (creation/edit date, status, author, ...).

**Comment by MichaelMure** [comment]
Alright, there is now a whole new layer that maintain in memory and on disk an excerpt of each bug (creation/edit time, status ...). This layer also provide a fast sorting without having to load all bugs in memory.

Next steps:

- add the filtering
- expose the filtering/sorting in the graphql API
- add the last mile code to have these feature in each UI

**Comment by MichaelMure** [comment]
Now the big question is, how this filtering/ordering should be done in the CLI ? I see two options:

- regular CLI flags: `git bug ls -state open -sort comments -order asc`

- a micro language, as Github do: `git bug ls "is:open sort:comments-desc"`

On Github, we have the convenience of having a web UI with dropdown and buttons that write this query, while still having the power to edit it manually. Not so much in a CLI interface.

It would be neat to have a common query format for all UIs though.

I'm inclined to go for the first option as the termui will give the "easy to use UI" in a terminal, leaving the CLI for automated interaction or simple manual tasks.

**Comment by MichaelMure** [comment]
Also, a micro language can be added later.

**Comment by MichaelMure** [comment]
And those are done as well ! That was a journey in itself ...
