### ISSUE TITLE
termui not displaying anything (on mingw)

### ISSUE THREAD

**Issue by hgtok** [MichaelMure/git-bug#222]
tested git-bug.exe 0.5.0 (both 386, amd64) on win10 (x64) and win7 (x64)

Installation steps:
1. extract PortableGit 2.23.0 to `C:\PortableGit\`
2. copy `git-bug.exe` to `C:\PortableGit\usr\local\bin\`
3. run PortableGit `git-bash.exe` (MinGW)
4. cd to git project
5. `git bug user create`
6. `git bug termui` << nothing is shown

Any flags to enable verbosity/debug to see what's wrong?

(Update 4 Oct)
* Found a workaround for this issue:
`winpty git bug termui`
However the interactive UI get sluggish after exiting the subprocess editor (e.g. create new bug, add comment)

**Comment by A-Hilaly** [comment]
FWIK there are no flags to enable verbosity for `git bug termui`. Is there any specific exit status or visual bug we can investigate ?

**Comment by MichaelMure** [comment]
What terminal are you using ?

Does other commands like `git bug add` of `git bug ls` work ?

**Comment by hgtok** [comment]
![image](https://user-images.githubusercontent.com/11731575/65929633-6fb45680-e435-11e9-882d-5b5a6a072c2a.png)

just hangs there..

**Comment by hgtok** [comment]
![image](https://user-images.githubusercontent.com/11731575/65929719-be61f080-e435-11e9-87a8-e75a53721ff2.png)

no issue with `git bug add` or `git bug ls`..

**Comment by MichaelMure** [comment]
Could you try another project using gocui to see if it's git-bug or not ? https://github.com/awesome-gocui/gocui#projects-using-gocui

**Comment by hgtok** [comment]
@MichaelMure i'm not sure how to use gocui to test this issue.. none of them appears to offer a bash terminal..

Or do you mean to `git clone` any one of the projects, and try `git bug termui` on them using official Git client?

**Comment by MichaelMure** [comment]
I mean install one project that use the gocui library (say, https://github.com/gulyasm/jsonui/releases) and test if it works properly. If not, it's likely that gocui is broken, not git-bug.

**Comment by hgtok** [comment]
I think we narrowed it, same issue also appears for jsonui

MinGW: `cat test.json | ./jsonui_windows_amd64.exe`
Result: not working

DOS: `type test.json | jsonui_windows_amd64.exe`
Result: working!

This lead me to test git-bug on msdos:
MSDOS: `git-bug_windows_amd64.exe termui`
Result: working!

(But it errors out when I try to create "new bug" on MSDOS, looking for `sh`. lol )
![image](https://user-images.githubusercontent.com/11731575/65971018-22b69b80-e49a-11e9-96eb-b2b647163ae0.png)

Have updated bug title to reflect MinGW, as that is my use case

**Comment by MichaelMure** [comment]
So it's a gocui compatibility problem. Not much we can do here.

You might want to open an issue at https://github.com/jroimartin/gocui (the original project) and https://github.com/awesome-gocui/gocui (a more maintained fork).

**Comment by hgtok** [comment]
Found a workaround for this issue:
`winpty git bug termui`

However the interactive UI get sluggish after exiting the subprocess editor (e.g. create new bug, add comment)

**Comment by MichaelMure** [comment]
Closing as it's now a 3 year old ticket. Feel free to reopen if it's still a problem.
