### ISSUE TITLE
Data model: Why use go-serialized data?

### ISSUE THREAD

**Issue by hoijui** [MichaelMure/git-bug#226]
I liked reading the data model! made me dream.. thank you! :-)
but I was wondering, why you chose to store `Operation`s/`OperationPack`s as go-serialized data, instead of an open format like JSON/YAML/Turtle or the like.
As much as I can see, this (together with a missing data-model-version) is the only thing that limits other software using the same data-model.
The only reason I could imagine, is performance. Did you make benchmark comparisons?

**Comment by MichaelMure** [comment]
git-bug does use JSON. Maybe the documentation is outdated or unclear ? Have a look at this thread: https://github.com/MichaelMure/git-bug/issues/5#issuecomment-420689243

**Comment by hoijui** [comment]
ahh thanks!
Indeed (at least to me) the documentation is unclear then (or outdated). I will try to formulate it so it reflects this.
