### ISSUE TITLE
import error: issue creation: Multiple matching bug found

### ISSUE THREAD

**Issue by agentofuser** [MichaelMure/git-bug#230]
I cloned the git-bug repo, ran `git bug pull`, then configured the bridge and ran `git bridge pull` and got this error:

```
❯ gu bridge pull
import error: issue creation: Multiple matching bug found:
4261bebb63ffaac33416003a2aa62a5a12df01b0
678b0eccf6bae77dc47ec71804b6a58f3cfdc4aa
Successfully imported 0 issues and 0 identities with default bridge
```

Is there a way for me to manually fix this? Should I have configured and pulled the bridge first then run `git bug pull`?

**Comment by MichaelMure** [comment]
Hey, so we figured out that one, what happened is that a long time ago I pushed all my imported issues, cleared my local repo, imported and pushed again. So the issue where duplicated. Not an actual bug and should not happen in a normal situation. Data is fixed now.

If you want to clear your local data, there is the commands to run in the makefile: https://github.com/MichaelMure/git-bug/blob/master/Makefile#L35-L46
