### ISSUE TITLE
unknown refname: format lstrip=-1

### ISSUE THREAD

**Issue by frodeaa** [MichaelMure/git-bug#24]
```bash
$ git --version
git version 2.11.0

$ git bug show 0178f12
Error: fatal: unknown refname: format lstrip=-1
Usage:
  git-bug show <id> [flags]

Flags:
  -h, --help   help for show

fatal: unknown refname: format lstrip=-1
```

support for `git for-each-ref --format '%(refname:lstrip=-1)'` was
added [2.13.2](https://git-scm.com/docs/git-for-each-ref/2.13.2)

**Comment by MichaelMure** [comment]
2.13.2 was released a year ago, so i guess it make sense to support previous version as well.

It should be fairly easy to fix, there is only one place where this is used.
