### ISSUE TITLE
Add a default value in prompts, selectable with [Enter]

### ISSUE THREAD

**Issue by jedahan** [MichaelMure/git-bug#252]
Maybe this could only auto-select if theres only one repo, so you can just press enter a bunch, and maybe it should be for other inputs as well.

**Comment by MichaelMure** [comment]
Make sense to me.

**Comment by MichaelMure** [comment]
I generalized the prompt code recently. I think prompt have a default value where that's possible. Feel free to reopen if you find one where it would make sense.
