### ISSUE TITLE
bridge configure documentation incorrect

### ISSUE THREAD

**Issue by mitra42** [MichaelMure/git-bug#266]
The documentation for getting this setup is very sparse so forgive me if I'm missing something :-)

I'm trying to set this up to mirror the bug tracker for the internetarchive/dweb-mirror project that I lead. 

I've installed the release 5.0 `git-bug_darwin_amd64` from https://github.com/MichaelMure/git-bug/releases/tag/0.5.0 and renamed as `git-bug`

I've not created any local issues, since I want to mirror the tracker at Github .

I'm somewhat guessing but the README at https://github.com/MichaelMure/git-bug/blob/master/README.md says  
```
git bug bridge configure \
    --name=mybridge \
    --target=github \
    --url=https://github.com/michaelmure/git-bug \
    --token=$TOKEN
```
first issue is that it doesn't explain what $TOKEN is - so I omitted it for now (which might be wrong)

I'm presuming I should cd into the directory where I've cloned the repo, as I would for any other git action on it, but I then see this ... 
```
dweb-mirror mitra$ git bug bridge configure --name=dmgithub --target=github --url=https://github.com/internetarchive/dweb-mirror
Error: unknown flag: --name
Usage:
  git-bug bridge configure [flags]

Flags:
  -h, --help   help for configure

```
Which suggests there is no --name parameter to `git bug bridge configure`. 

So I try the help ...
```
git bug bridge configure -h
Configure a new bridge.

Usage:
  git-bug bridge configure [flags]

Flags:
  -h, --help   help for configure
```
Oops - even less helpful than the README :-) 

Is there a better place for the docs, or does this only work from some version since 5.0 (which was in April).

**Comment by MichaelMure** [comment]
Those features are not yet released and will be in the upcoming 0.6.0. You can try building from master if you want but that's at your own risk.

**Comment by mitra42** [comment]
What's the ETA on 0.6.0 - going to need the bridge for it to be any use, and no need to pound on pre-release code on something I'm not familiar with, I won't know if the bugs are me or the code. 

Looks a great project anyway, and look forward to testing it.

**Comment by MichaelMure** [comment]
It's pretty much at the door. We are in the final phase of testing, checking if everything is as it should. The release will be pretty much identical if not exactly. If you wanna help testing, that'd be cool :)
