### ISSUE TITLE
feat: landing page

### ISSUE THREAD

**Issue by KeziahMoselle** [MichaelMure/git-bug#269]
I think it can be a great idea to create a landing page for this project.
We can :
- Download Git Bug
- Overview of the project (screens and features)
- Some documentation (exhaustive CLI commands and options)

**Comment by MichaelMure** [comment]
I would consider that lower priority than building the webUI but by all means, go ahead if you want to work on that :)

FYI, I have a bunch of domain names including git-bug.com

**Comment by KeziahMoselle** [comment]
You're right, it's not a priority at all, just wanted to create this issue to at least track it

**Comment by MichaelMure** [comment]
Closing as it's not a priority and will come naturally if it's needed one day.
