### ISSUE TITLE
Terminal shell completion for Windows

### ISSUE THREAD

**Issue by ghost** [MichaelMure/git-bug#27]
I dig how the bash completion code gen works. If anyone knows how to do the same on windows we could codegen what it needs to work also.

Then the question is what windows shell to target ? Good old CMD or Piwershell ? I don't know what the advice would be for Windows 10 these days 

I guess it's also important to get feedback from other Devs ( thumbs up for example ) so we know if this is worth the effort too.

**Comment by MichaelMure** [comment]
You would have to add the feature in [cobra](https://github.com/spf13/cobra), the library I use for parsing command line flags and all.

They would certainly be happy to have that, see https://github.com/spf13/cobra/issues/387

**Comment by MichaelMure** [comment]
PowerShell completion is now available: https://github.com/MichaelMure/git-bug/tree/master/misc/powershell_completion

@gedw99 could you test it ? I have no idea how that work myself :)
