### ISSUE TITLE
question: is anyone working on a JIRA bridge?

### ISSUE THREAD

**Issue by felsgaertner** [MichaelMure/git-bug#270]
Hi, 

as JIRA is often used for agile development (scrum, kanban, etc.), and as this project has 100+ forks, I would like to ask the community if there is someone working on a JIRA bridge.

Thanks,
Volker

**Comment by MichaelMure** [comment]
Yes, @cheshirekow is working on it over there: https://github.com/MichaelMure/git-bug/pull/250
