### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#28]
It would be neat to have a logo for git-bug.

Someone to assist here ?

**Comment by j-f1** [comment]
Perhaps a 🐞 with the Git logo on its back?

**Comment by MichaelMure** [comment]
Hooo, I like this idea !

**Comment by j-f1** [comment]
The [Git logo](https://git-scm.com/downloads/logos) is licensed under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/), meaning we can use it as long as we credit it. The Git name, though, has [stricter rules](https://git-scm.com/about/trademark).

**Comment by vandesign** [comment]
Hi guys! What do you think about this mockup? The idea is a trap for bugs inside git.
![git-bug--logo-concept](https://user-images.githubusercontent.com/5607130/44524780-7c6d6380-a6e7-11e8-9010-cb11be9c6838.png)

**Comment by afranke** [comment]
I like this initial direction, but I have a few issues with that first iteration:
* it is a little too generic and could work for a lot of things that aren’t git-bug,
* even if the git logo is freely licensed, using it as a base is a delicate matter and I would avoid it.

How about keeping the idea of the graph/tree, but using small symbolic bugs (insects) as nodes?

**Comment by vandesign** [comment]
If you reduce the logo, small details will be lost. And the bug in each node is terrible. ) But I'll think about it.

**Comment by MichaelMure** [comment]
This is great, the git logo even looks like wings, as if git-bug is powered by git.

It would also probably look nice when declined in 3D.

**Comment by vandesign** [comment]
![image](https://user-images.githubusercontent.com/5607130/44542179-bacd4780-a714-11e8-81f6-1cb48a4e57b5.png)
![image](https://user-images.githubusercontent.com/5607130/44542200-cc165400-a714-11e8-8411-183915b0a40c.png)

**Comment by vandesign** [comment]
> It would also probably look nice when declined in 3D.

what do you mean, @MichaelMure ?

**Comment by MichaelMure** [comment]
@vandesign before you showed your version I was thinking about a stylized 3d projection, something  like this with the git logo on the side:
![image](https://user-images.githubusercontent.com/294669/44545677-03393500-a716-11e8-9f6f-ebb8349b5d25.png)

Note: this is just a quick image search to explain, I'm not saying it should look like this. The flat 2d design works well :)

**Comment by MichaelMure** [comment]
Also, a lot of thanks, it's so awesome to see these kind of contribution :+1:

**Comment by vandesign** [comment]
I'll still work on the versions.

**Comment by vandesign** [comment]
Simplified form.
![git-bug--logo-concept--03](https://user-images.githubusercontent.com/5607130/44675197-79041000-aa38-11e8-8cb0-71baee400120.png)
![git-bug--logo-concept--04](https://user-images.githubusercontent.com/5607130/44675198-79041000-aa38-11e8-96b0-7a7892e65207.png)

**Comment by MichaelMure** [comment]
That's great @vandesign ! Out of curiosity, what software do you use ? Is that a vector format ?

**Comment by MichaelMure** [comment]
Also, would you like to continue iterating or is that the version we should use ?

**Comment by MichaelMure** [comment]
An open format would be best, so SVG.

Now, another question will be the license to use. git-bug is released under the GPLv3+ license but we might want to use a different one for the logo. Of course, as the author you have your say on this.

**Comment by vandesign** [comment]
> Now, another question will be the license to use. git-bug is released under the GPLv3+ license but we might want to use a different one for the logo. Of course, as the author you have your say on this.

I'm not an expert in licensing and I leave it to the community.

**Comment by vandesign** [comment]
The final versions of the files will be tomorrow.

**Comment by x4m3** [comment]
the logo looks awesome @vandesign !

for the license, i dont think gpl would be the best for an icon, maybe use a [creative commons license](https://choosealicense.com/licenses/cc-by-sa-4.0/)? iirc, the cc-by-sa-4.0 is the license used on wikipedia for images and documents.

but since you're the author of the logo, it's your decision :)

**Comment by vandesign** [comment]
As Git logo is licensed under CC BY 3.0, we will use it.
I prepared 3 variants of the logo in the SVG format.
[git-bug--logo.zip](https://github.com/MichaelMure/git-bug/files/2331939/git-bug--logo.zip)

**Comment by MichaelMure** [comment]
![git-bug--logo--alpha](https://user-images.githubusercontent.com/294669/44804354-5f420480-abc1-11e8-985c-2cd8a87b2586.png)

**Comment by MichaelMure** [comment]
![git-bug--logo--alpha--flat](https://user-images.githubusercontent.com/294669/44804363-679a3f80-abc1-11e8-87f2-bf651dfab580.png)

**Comment by MichaelMure** [comment]
Everyone, please select the best logo by reacting with a :heart: on one of the two comment above.

**Comment by vandesign** [comment]
And what about the third version? Without a white stroke.

**Comment by MichaelMure** [comment]
I agree it looks nicer, but it's less easy to use if you don't have a white background. Let's have it in the contest though :-)

**Comment by vandesign** [comment]
> I agree it looks nicer, but it's less easy to use if you don't have a white background.

Yes. I remember that. In fact, there is a white background. ) In git-bug--logo--alpha--flat--bg.svg

![2018-08-29_21-47-03](https://user-images.githubusercontent.com/5607130/44808599-51967a00-abd5-11e8-9ab7-2a77b21516b5.png)

**Comment by MichaelMure** [comment]
@vandesign could you give me the svg for the logotype as well ?

**Comment by x4m3** [comment]
suggestion: what do you think if you include the git-bug logo at the top of the webui, with a link to this git repo? kinda like github does

**Comment by tplk** [comment]
> As for the license, CC BY-SA 4.0 is probably a good choice.

Is it possible to sublicense Apache v2 font under CC-BY-SA though?

**Comment by MichaelMure** [comment]
> Is it possible to sublicense Apache v2 font under CC-BY-SA though?

[yes](https://www.quora.com/What-does-it-mean-for-any-font-to-have-an-Apache-2-0-license-Does-that-mean-I-can-use-that-font-freely-for-commercial-purposes)

**Comment by MichaelMure** [comment]
> suggestion (but kinda off topic) : what do you think if you include the git-bug logo at the top of the webui, with a link to this git repo? kinda like github does

In term of web design, having a logo top left with a link has to be "go to the root of the website"

For git-bug, that means either:

- go to the list of repositories for a multi-repo webui
- go to the list of bugs for a single repo webui

Having a link somewhere to the github project make sense though, just not there.

**Comment by x4m3** [comment]
now that you say it , you're right, what was i thinking

> Having a link somewhere to the github project make sense though, just not there.

maybe at the end of the webui? like in the footer

**Comment by vandesign** [comment]
Hi!
I made the final versions of the files.

- Symbol on a white background.
- Logo without shadow.
- Logo with shadow.

To prevent the use of the logo on a dark background, I made only the option with a white background. Other versions suggest to remove.

[git-bug.zip](https://github.com/MichaelMure/git-bug/files/2345465/git-bug.zip)

**Comment by MichaelMure** [comment]
Alright, I merge the PR in master, git-bug now has officially a logo

:tada: :tada::tada::tada::tada::tada:

@vandesign Thank you so much !

**Comment by MichaelMure** [comment]
It would have been nice to use the logotype in the readme, but as @tplk said, it doesn't work on a dark background.
