### ISSUE TITLE
feat: Close bug from termui's show view

### ISSUE THREAD

**Issue by jacobsmith** [MichaelMure/git-bug#29]
Hello,

Thanks for your work on this! I looked through the source code and I don't think I'm missing anything, but it would be great to be able to close a bug via `termui` when you are in a particular bug's view.

If that is in fact a feature that's missing, I'd be happy to work on a PR to add it. My apologies if it already exists and I just haven't figured it out yet! :smile:

Thanks!

**Comment by MichaelMure** [comment]
It's indeed a missing feature, PR welcome :+1: 

Just a head's up, bugs state are likely to evolve past the simple open/closed that we have now and support more states, maybe even arbitrary state. That won't happen in the short term though.
