### ISSUE TITLE
Unable to create a bridge due to SSL error

### ISSUE THREAD

**Issue by Flyounet** [MichaelMure/git-bug#318]
I have to connect to a Gitlab CE where the SSL certificate is not correct (self-signed).

`git-bug` **0.6.0** produces :

```
$: git bug bridge configure
[1]: github
[2]: gitlab
[3]: launchpad-preview
target: 2
name [default]: GL
Gitlab base url:
[0]: https://gitlab.com
[1]: enter your own base url
Select option: 1
Base url: https://fqdn

Detected projects:
[1]: https://fqdn/Team2/Tech-API

[0]: Another project

Select option: 1
You can generate a new token by visiting https://gitlab.com/profile/personal_access_tokens.
Choose 'Create personal access token' and set the necessary access scope for your repository.

'api' access scope: to be able to make api calls

Enter token: abcdefghijklmonpqrstuvwxyz
Error: project validation: wrong token scope ou inexistent project: Get https://fqdn/api/v4/projects/Team2%2FTech-API: x509: certificate has expired or is not yet valid
```

git works correctly with this server by using in the `~/.gitconfig` :

```.gitconfig
[http]
        sslverify = false
```

N.B. : I also tried to add the above configuration in the `.git/config` with same result.

**Comment by MichaelMure** [comment]
Using `http.sslverify` sounds like a good solution. Should be fairly easy to do as long as it's supported in `go-gitlab`.

**Comment by MichaelMure** [comment]
The way is apparently to disable SSL verification in the golang HTTP client itself: https://stackoverflow.com/a/12122718

**Comment by MichaelMure** [comment]
Closing as this issue is not 2 year old and a lot have changed. Please reopen if needed.
