### ISSUE TITLE
bridge pull fails with "Error: message is not fully printable"

### ISSUE THREAD

**Issue by daurnimator** [MichaelMure/git-bug#339]
Trying to pull the ziglang repository it eventually fails with:
```
import issue: Compiler abort on unicode in strings in certain places
Error: message is not fully printable
Usage:
  git-bug bridge pull [<name>] [flags]

Flags:
  -h, --help   help for pull

```

Possibly the issue its failing on? https://github.com/ziglang/zig/issues/258

**Comment by MichaelMure** [comment]
Hmm, the text should always go through https://github.com/MichaelMure/git-bug/blob/master/util/text/transform.go#L11-L31 to be cleaned of weird characters. It later is checked with https://github.com/MichaelMure/git-bug/blob/master/util/text/validate.go#L21-L34.

Maybe a code path is missing the cleanup ?

**Comment by MichaelMure** [comment]
What version are you using ?

**Comment by daurnimator** [comment]
git-bug version: -dev-
System version: amd64/linux
Golang version: go1.13.4

**Comment by MichaelMure** [comment]
You need to compile with `make` to have the version set properly. Also, try the master branch, a lot changed.

**Comment by daurnimator** [comment]
> You need to compile with `make` to have the version set properly.

I use the AUR package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=git-bug

I'm running an import now and haven't hit the same issue (yet). I'll close this bug in the morning if it finishes.

**Comment by MichaelMure** [comment]
Yeah, that's https://github.com/MichaelMure/git-bug/issues/315
