### ISSUE TITLE
feat: bug full text search

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#342]
It would be nice to search in bugs with keywords. To do that, we need a pre-computed index of words to keep a reasonable performance.

Such index *could* store the number of occurrence of a word within a bug. Ideally it would filter the most common words. Possibly, this index would be common to all bugs. Also, this index needs to support updating when a new operation is added.

**Comment by MichaelMure** [comment]
https://github.com/go-ego/riot or https://github.com/blevesearch/bleve might fit the bill.

**Comment by MarkoShiva** [comment]
That would be great feature. Btw great work on the tracker by now. :)

**Comment by MichaelMure** [comment]
Hey people, it's working now ! Thanks @skmgoldin !
