### ISSUE TITLE
Implement Gitea bridge

### ISSUE THREAD

**Issue by strk** [MichaelMure/git-bug#349]
It would be great to have one, be it a first step toward [integration](https://github.com/MichaelMure/git-bug/issues/80) or not

**Comment by MichaelMure** [comment]
Any volunteer around ?

**Comment by tredoe** [comment]
There is also other self-hosted Git service implemented in Go: [Gogs](https://github.com/gogs/gogs)

**Comment by AtomToast** [comment]
afaik gitea is a fork from gogs with a different development philosophy and from what I saw also more features

**Comment by 6543** [comment]
I might have a look at this ...

**Comment by GalaxySnail** [comment]
Not stale.

**Comment by WillForan** [comment]
for reference, I think PR #1077 is the most recent (July 2023) effort to implement the bridge and issue #80 addresses gitea integration on the whole

**Comment by sudoforge** [comment]
I'm hestitant to add new bridges at all given that it adds to the maintenance burden of `git-bug` and its core features (imagine a world in which there is a bridge for _every other issue management platform_ -- who is going to maintain it?). I'm much more in favor of maintaining a common bridge interface and supporting a "plugin system", allowing the community to maintain specific bridges outside of `git-bug`.

**Comment by sudoforge** [comment]
Closing in favor of keeping #80 as the source of truth for the Gitea integration request.
