### ISSUE TITLE
git-bug and git-ssb validation

### ISSUE THREAD

**Issue by qcu** [MichaelMure/git-bug#356]
Big git-bug fan here. ❤

I was just testing git-bug together with [git-ssb](https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256), and need to look into this further, to see what is causing what appears to be a git bug push write error. [1]

Note that regular pushes, git-ssb with `git push [ssb|origin] branch` are working fine.

[1]: $ git bug push ssb
```
        if (err) throw err
                 ^
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:392:12)
    at writeOrBuffer (_stream_writable.js:374:5)
    at Socket.Writable.write (_stream_writable.js:314:12)
    at /usr/local/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:61:18
    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-git-remote-helper/index.js:469:11
    at /usr/local/lib/node_modules/git-ssb/node_modules/pull-git-remote-helper/lib/pkt-line.js:31:9 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

error: failed to push some refs to 'ssb://%R264c0DkGTUTmdUbcl844IL0KD6kPP7QGUpsnF0EfAY=.sha256'
```

**Comment by MichaelMure** [comment]
Hoooo, that's fun.

It seems to be a problem in git-ssb rather that git-bug itself. All the object created by git-bug are git legal (git itself created them). Maybe some kind of format badly assumed somewhere ?

**Comment by qcu** [comment]
Thanks! I partially opened this for general awareness of git-ssb, as an option for git-bug.

[@cel](https://viewer.scuttlebot.io/@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519) (git-ssb author) [noted](https://viewer.scuttlebot.io/%25F%2Bp%2BCStxaYdnKdSQ%2F2LlnynR%2ByPbcsAXLG%2FMOF02t64%3D.sha256) that I was using an old version of git-ssb, and we have confirmed the ability to `git bug push origin` to git-ssb remotes.

> The EPIPE might be from a bug fixed in a newer version of git-ssb. The version that you get from using npm install is old. The latest one is distributed via ssb-npm. There is also a binary build of the latest version, which may be easier than using ssb-npm: [%9/2M5....](https://viewer.scuttlebot.io/%259%2F2M5lUETpt7uVbbf%2BPocNHqtwWpPyIkQP3TPoELPBc%3D.sha256)

Onward to enhancement git-bug bridge for git-ssb tracker #357 

git-bug + git-ssb, fully decentralized, FTW!
