### ISSUE TITLE
git-bug GitLab bridge does not correctly import labels

### ISSUE THREAD

**Issue by mkroehnert** [MichaelMure/git-bug#360]
I heard of git-bug a couple of days ago and gave it a try today.
But first of all, I'd like to thank you for creating and maintaining this great project.

Now to the issue I encountered.
I have a private project hosted on GitLab.com and I used git-bug to pulll the issues from the tracker with the GitLab bridge.
All issues were downloaded and converted, but I noticed, that the labels were missing for all except the latest issue.

To test this, I created a dedicated test project: https://gitlab.com/mkroehnert/git-bug-issue-test/-/issues
After pulling the issues, none of them had a lable atteched.

OS: NixOS Linux 19.09 stable
git-bug: 0.7.0 (from NixOS unstable)

**Comment by MichaelMure** [comment]
It seems to be a problem in the iterator, it doesn't return any LabelEvent after the first one.

cc @A-Hilaly

**Comment by MichaelMure** [comment]
Should be fixed by https://github.com/MichaelMure/git-bug/pull/363

**Comment by mkroehnert** [comment]
@MichaelMure that was really quick. Thanks a lot.
