### ISSUE TITLE
Gitlab bridge misbehaving with identities

### ISSUE THREAD

**Issue by toyg** [MichaelMure/git-bug#369]
What I've done:
1. created a user and configured a bridge, specifying my Gitlab username as login and a valid token
2. created an issue
3. successfully pushed
4. edited the issue on gitlab (added labels)
5. pulled. The issue was duplicated, and the identity appeared different (had the full name)
6. deleted and re-created the bridge, this time with my email as login and the same token as before
7. removed old auth with `git bug auth rm <old_auth_id>`

At this point, this is the situation:
```bash
$> git bug bridge auth
Error: unknown credential type ""
$> git bug bridge pull
Error: unknown credential type ""
$> git bug bridge auth add-token <my_token> -t gitlab -l <my_email>
Error: this user is already tagged with a different gitlab login
```

What do?

**Comment by MichaelMure** [comment]
I believe this is due to https://github.com/MichaelMure/git-bug/issues/434 that I just found out. Let's close this one
