### ISSUE TITLE
New issues are created at start of Unix time

### ISSUE THREAD

**Issue by Irubataru** [MichaelMure/git-bug#37]
Creating new issues using either new or termui will both create an issue at unix zero time (1970/01/01). This is a newly introduced bug as it happens with the current master branch (commit 0728c00, fetched and built with `go get`), but is not an issue in the latest release (v.0.2.0).

**Comment by MichaelMure** [comment]
I had a look, it's probably because the field `unixTime` of `OpBase` is not exported anymore. I needed to have `UnixTime()` in the `Operation` interface.

So this field is either not serialized or ignored when deserializing.

I will need to find a good naming now ...
