### ISSUE TITLE
Implement git-bug bridge to export to file

### ISSUE THREAD

**Issue by rerobins** [MichaelMure/git-bug#370]
Would also implement #45

I'm looking to be able to build something that would dump out a list of the bugs that are defined in the repositories so I can build a display/track multiple repositories that are using git-bug.  

I don't believe that it would make sense for this bridge to handle the importing of functionality.  JSON would be fine, but really any structured format would be good.

**Comment by MichaelMure** [comment]
Can you detail a bit more why you need that ?

Using the bridge infrastructure would work but I'm not sure that's really needed. A simple export command would do as well it seems.

**Comment by rerobins** [comment]
I'd like to have a display that is similar to the [dashboard on GitHub](https://github.com/issues) that can give me an overview of all of the repositories that I'm working on.  I can't do this with git-bug at the moment without opening up all of the repositories.  The data could be used to auto-generate reports that I can give to customers showing progress. 

It doesn't have to be a bridge, I just figured that a bridge would be the easiest way to get the data out of the system since you're already pulling the data out of the system to send it to other 3rd party services.

**Comment by MichaelMure** [comment]
Closing in favor of https://github.com/MichaelMure/git-bug/issues/392
