### ISSUE TITLE
feat: Better ZSH shell completion

### ISSUE THREAD

**Issue by Irubataru** [MichaelMure/git-bug#38]
To make browsing issues easier it would be really great if we could have shell completion on par with git completion in zsh (not sure how well it works in bash). Ideally typing `git bug show <TAB>` would show a list of bugs similar to how `git checkout <TAB>` shows a list of branches and commits (see picture).

![git_tab_complete](https://user-images.githubusercontent.com/5611071/45045080-da943200-b069-11e8-9865-dc896671747d.png)

**Comment by MichaelMure** [comment]
It will depend on better support in [cobra](https://github.com/spf13/cobra).

There is a [PR open](https://github.com/spf13/cobra/pull/646) for that but the author is on hold for personal reason.

**Comment by Irubataru** [comment]
I see, interesting. I sort of assumed that shell completion was handled by separate completion scripts, but I guess it makes sense that you use the git-bug executable to handle lookup of the information that zsh etc would need.

**Comment by MichaelMure** [comment]
Better ZSH completion landed: https://github.com/MichaelMure/git-bug/tree/master/misc/zsh_completion

@Irubataru could you give it a try ?

**Comment by Irubataru** [comment]
Sorry for the late reply, but I finally got around to trying it out and when I try to autocomplete `git bug show` I get the following message:

```
_arguments:comparguments:325: invalid option definition: (-f --field)-f[Select field to display. Valid values are [author,authorEmail,createTime,humanId,id,labels,shortId,status,title,actors,participants]]:
_arguments:comparguments:325: invalid option definition: (-f --field)-f[Select field to display. Valid values are [author,authorEmail,createTime,humanId,id,labels,shortId,status,title,actors,participants]]:
_arguments:comparguments:325: invalid option definition: (-f --field)-f[Select field to display. Valid values are [author,authorEmail,createTime,humanId,id,labels,shortId,status,title,actors,participants]]:
```
and if I try to tab complete `git bug ls` then I get

```
_arguments:comparguments:325: invalid option definition: (*-s *--status)*-s[Filter by status. Valid values are [open,closed]]:
_arguments:comparguments:325: invalid option definition: (*-s *--status)*-s[Filter by status. Valid values are [open,closed]]:
_arguments:comparguments:325: invalid option definition: (*-s *--status)*-s[Filter by status. Valid values are [open,closed]]:
```

I installed it wit the go get method, and placed the `git-bug` file in the folder you linked somewhere my zsh instance could find it.

**Comment by MichaelMure** [comment]
Ha, interesting. It's possibly because the completion is generated for `git-bug` and not `git bug`. 

The bash completion require a very minimal adaptor function: https://github.com/MichaelMure/git-bug/blob/master/commands/root.go#L44-L49

Unfortunately, I have zero knowledge about ZSH completion. Would you be able to fix that ?

**Comment by Irubataru** [comment]
I tried with both `git-bug` and `git bug`, and it makes no difference, so I am not sure if that is the issue. I think I found it though, it appears to be due to the brackets in the explanation strings, e.g. as you can see in line 141.

https://github.com/MichaelMure/git-bug/blob/aa4464dbba0b1e0ce39ae53e35971e6924d404d3/misc/zsh_completion/git-bug#L138-L146

I use zsh, but I have never tried to write completion for it. However, if you escape the inner brackets as `\[` and `\]` then I do not get those error messages anymore. I thought about making a quick PR for it, but it appears that you generate the completion scripts from go, so maybe you have to fix it at a different level. 

Also, there is no completion for completing issue numbers. If you look at the zsh file and the bash file, you can see that the bash file has a lot more logic in it. The zsh file only completes command names and optional argument strings. I played around with it for a bit and got something basic working, so maybe I could help out with that if I ever find the time, or is that something your framework should support by itself?

**Comment by MichaelMure** [comment]
The situation is that git-bug use Cobra as the command line parser, and this library can generate the ZSH completion. They just landed a complete rewrite of this, so it's possible there is a bug lurking somewhere. The code generating the file is there: https://github.com/spf13/cobra/blob/master/zsh_completions.go

As for the custom completion of bug ID, it seems that Cobra doesn't support that at the moment for ZSH: https://github.com/spf13/cobra/blob/master/zsh_completions.md

That said, it's very much in line with what they want to support (it's possible for bash). git-bug has the `ls-id` command so it would be pretty easy to plug there. Note though that all te git-bug commands support giving a simple prefix, so you don't need that much the completion.

**Comment by MichaelMure** [comment]
The bracket problem is fixed with this PR upstream: https://github.com/spf13/cobra/pull/899

**Comment by MichaelMure** [comment]
This has been working for long.
