### ISSUE TITLE
DOC,UBY: What do I specify for avatarURL? Gravatar? W3C DID?

### ISSUE THREAD

**Issue by westurner** [MichaelMure/git-bug#383]
First walkthrough: I'm doing `git bug user create` and I don't know what to specify when it asks for `Avatar URL:`?
https://github.com/MichaelMure/git-bug/search?q=avatar

Questions:
- Is it my gravatar profile URL, for example, or a path to profile image?
- Can I just leave this blank for now?

Possible solutions for improving usability (UBY):

- [ ] add an explanation in the CLI
- [ ] add an explanation in the docs. 

( "A Gravatar is a Globally Recognized Avatar."; they have a JSON API: 
https://en.gravatar.com/site/implement/profiles/ )

https://www.w3.org/TR/did-core/ ::

> Decentralized identifiers (DIDs) are a new type of identifier that enables verifiable, decentralized digital identity. A DID identifies any subject (e.g., a person, organization, thing, data model, abstract entity, etc.) that the controller of the DID decides that it identifies. These new identifiers are designed to enable the controller of a DID to prove control over it and to be implemented independently of any centralized registry, identity provider, or certificate authority. 

See: "Identity Management" #55

**Comment by MichaelMure** [comment]
This AvatarURL thing is not really fleshed out properly yet. It's any HTTP link pointing to an image. It's optional.

This should be replaced by storing the file in git really. Loading arbitrary image from the internet has security implications.

**Comment by westurner** [comment]
So I can just press Enter there without entering a URL?

**Comment by MichaelMure** [comment]
Yes
