### ISSUE TITLE
[gitlab] git-bug bridge pull stop on error, so issues are missing

### ISSUE THREAD

**Issue by vtexier** [MichaelMure/git-bug#384]
git-bug version: 0.7
gitlab server: GitLab Community Edition 12.10.2 

I get a bug (or feature) with the `bridge pull` command. `git-bug` do not crash, but stop importing after an error.

```bash
import error at id 975: label event creation: removed label: empty
imported 643 issues and 13 identities... 
```

Then...
- all issues after the error are missing.
- Many issue closed are open in git-bug.
```
GitLab: Open 76    Closed 697    All 773
git-bug: open 640    closed 3
```

If I run again the command, issues are added again so I have them twice !

```bash 
import error at id 975: label event creation: removed label: empty
imported 643 issues and 0 identities with git.duniter.org bridge
```
Then:
```
GitLab: Open 76    Closed 697    All 773
git-bug: open 1280     closed 6 
```

Was so close to heaven ! ;)

**Comment by MichaelMure** [comment]
Closing as it's a 2 year old issue and a lot have changed. Please reopen if needed.
