### ISSUE TITLE
Gitlab bridge push comments?

### ISSUE THREAD

**Issue by Eluminae** [MichaelMure/git-bug#389]
Hello there ! 

Just discovered git-bug and it seems awesome.

I got an issue, I think. I added a comment to my imported gitlab issue then I try to "git bug bridge push" but it keep telling me "exported 0 issues with gitlab bridge" and I don't see my comment in the gitlab issue view.

What am I missing ?

Ty by advance

**Comment by MichaelMure** [comment]
That should work. Do you get any errors ?

As you can see in the issues here, a bunch of others bugs have been found regarding the bridges, it might be related.

**Comment by Eluminae** [comment]
I don't have any errors.

**Comment by Eluminae** [comment]
I close this cause it is a duplicate of https://github.com/MichaelMure/git-bug/issues/366
