### ISSUE TITLE
Comments do not show up in termui until restart

### ISSUE THREAD

**Issue by Irubataru** [MichaelMure/git-bug#39]
First, this is another issue that only shows up in the most recent commit, but is not present in the release. Do you want these issues? If not I'll stop reporting them and wait for the next release.

The issue now is if I open the termui and register a comment on any issue, this comment will not appear in the termui until I restart it. It doesn't even refresh if I open a new issue in the termui and comment on that. See another gif showing the problem

![termui-issue](https://user-images.githubusercontent.com/5611071/45046586-7b84ec00-b06e-11e8-8dbf-8abbcdeb05bf.gif)

**Comment by MichaelMure** [comment]
Good catch :+1:
