### ISSUE TITLE
git tags for project don't match golang spec

### ISSUE THREAD

**Issue by ssgelm** [MichaelMure/git-bug#390]
The golang spec for tagged versions (https://blog.golang.org/publishing-go-modules) specifies that the version tags should be `vVERSION`, e.g. `v0.7.1`. Would it be possible for you to add tags in this format and modify your tooling to continue to do so moving forward?

Thanks!

**Comment by MichaelMure** [comment]
... woopsy

Do you think it would be a problem if I double tag the last release ?

**Comment by ssgelm** [comment]
I think that sounds safe...

**Comment by MichaelMure** [comment]
Last release has a proper tag.

It's also a release that fix a security issue.
