### ISSUE TITLE
Implement Sourcehut bridge

### ISSUE THREAD

**Issue by skyfaller** [MichaelMure/git-bug#394]
[Sourcehut](https://sourcehut.org/) is still in alpha, so it might be a moving target, but it would be great if we could somehow bridge to [their ticket-tracking system](https://man.sr.ht/todo.sr.ht/).

**Comment by MichaelMure** [comment]
API is here: https://man.sr.ht/todo.sr.ht/api.md

**Comment by 6543** [comment]
instead of what you did with jira, I'm also interested to have a go-lib to Sourcehut for the Gitea migration tool (https://github.com/go-gitea/gitea/issues/8689)

does somebody actually have started creating one?
