### ISSUE TITLE
feat: catch properly Ctrl+C / SIGINT in commands

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#42]
Right now, commands get killed by a SIGINT and the lock file is not properly removed.

As the cache is smart enough to see that the previous process is gone and clean the file, it's not that much of a problem, but it would be cleaner.

**Comment by auyer** [comment]
I'll start looking into this issue.
Are there exported functions responsible by creating and removing the lock files ? If there are, the solution is even cleaner and I wont need to re-write any code.

**Comment by MichaelMure** [comment]
Thanks.

What you need to trigger is `RepoCache.Close()`, that is the `backend.Close()` that you can see in most of the commands.

**Comment by MichaelMure** [comment]
Dealt with by @auyer :+1:
