### ISSUE TITLE
Next Release Date

### ISSUE THREAD

**Issue by ogirginc** [MichaelMure/git-bug#431]
Hi Micheal 👋 Thanks for this useful & thoughtful project!

Quick question: When is the next release planned? The lastest one was nearly 4 months ago. Features like https://github.com/MichaelMure/git-bug/pull/371 are merged but can not be used.

**Comment by MichaelMure** [comment]
No date planned. At the moment `master` is in the middle of fairly big under the hood improvements. Those will take time to settle and will require https://github.com/MichaelMure/git-bug-migration/ to be finalized to migrate the existing repo. I also have an actual job so expect at least two more months, likely more.
