### ISSUE TITLE
[bridge] auth token are not removed properly in git config

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#434]
When removing a bridge credential, a git command is executed in the repo to remove the corresponding sections in the global config. It seems that this command only match part of the entries to remove, leaving a broken credential behind.

The git config is quite akward to work with, maybe the best way would be to just migrate to the go-git backed Repo https://github.com/MichaelMure/git-bug/pull/412 and be done with it.

**Comment by MichaelMure** [comment]
`master` now use go-git with a dedicated keyring. This issue is no longer a concern.

**Comment by smheidrich** [comment]
@MichaelMure I still have this exact issue in the latest release binary (March 21, 2021). Have the relevant commits not made it into that release yet or is this a regression?

**Comment by MichaelMure** [comment]
It's not released yet. The last release was just addressing a security issue.

**Comment by smheidrich** [comment]
@MichaelMure I see, thanks!
