### ISSUE TITLE
CLI Export Command

### ISSUE THREAD

**Issue by andyl** [MichaelMure/git-bug#45]
In #5 @MichaelMure settled on JSON as a serialization format.

Feature request: add a CLI command to export the issue repository.

Something like: `git bug export` that just exports the whole issue repo as JSON would be great.

**Comment by MichaelMure** [comment]
Alright, a few questions:

- do you need the data of a single bug or the repo as a whole ?
- do you need the compiled state of the bug or the history as well ?

I may keep `git bug import`/`git bug export` for the bridge operation with external bug trackers, but this feature might be added as a flag of `git bug show` for example.

**Comment by andyl** [comment]
I need a current snapshot which returns all issues in the repo.  Don't need the commit history.

For each issue:
- some sort of unique issue ID
- title, description, status, labels
- comments

**Comment by MichaelMure** [comment]
Does it have to be the whole repo in one go or could it be exporting bugs individually and a way to iterate them ?

**Comment by MichaelMure** [comment]
Just a node, if you care about the bandwidth, you would be better at using `git bug pull` to get the delta since the last sync as compressed blob and query bugs locally.

**Comment by MichaelMure** [comment]
Closing in favor of https://github.com/MichaelMure/git-bug/issues/392
