### ISSUE TITLE
Bridge - issues not showing up from github

### ISSUE THREAD

**Issue by mitra42** [MichaelMure/git-bug#451]
I've got a github project mitra42/webForth

I've have, or believe I have, a configured bridge with it. 

`git bug pull` says 
```
Fetching remote ...

Merging data ...
```
So I'm presuming it is connected since there are no error messages

`git bug bridge auth` shows me a listing for github with a token and the right login id "mitra42"

BUT ... `git bug ls` shows no issues (there is at least one issue there).

Happy to help debug ....

**Comment by MichaelMure** [comment]
`git bug pull` is for the native workflow of git-bug (push/pull to git remotes). You are looking for `git bug bridge pull` ;)

**Comment by MichaelMure** [comment]
It's a common mistake though, not sure how to make it more obvious/discoverable.

**Comment by mitra42** [comment]
I'm not sure - I think you've made the UI more complex than necessary.  Normally when I do `git pull` it brings stuff to my local laptop from the remote git (typically github or gitlab), why wouldn't `git bug pull` do the same for the issues i.e. I can't understand what `git-bug pull` would do that is different from `git bug bridge pull` ?

P.S. I suggest re-opening the issue, as a UX issue if its not a bug !
