### ISSUE TITLE
termui: configurable color scheme

### ISSUE THREAD

**Issue by AtomToast** [MichaelMure/git-bug#453]
I use a colorscheme with a quite bright blue color which leads to the statusbar being basically unreadable.

![image](https://user-images.githubusercontent.com/27757087/91881468-0d7d5a80-ec71-11ea-9e9d-1db736f9c66a.png)

I found [this pr](https://github.com/MichaelMure/git-bug/pull/428) but they also only added hardcoded values. Is there any simple way to add support for colors? Maybe through xresources or something even?

**Comment by MichaelMure** [comment]
I'm still looking for the right way to do those things. From the app itself, I have no idea what kind of theme is used.

**Comment by AtomToast** [comment]
Have you just considered letting the users define colors for the application on their own? Maybe even with 256 or truecolor support.

However I am aware that the application currently doesn't appear to have any kind of config file. Which is why I suggested xresources, however this probably isn't perfect either, since some people may be running wayland or no graphical server at all

**Comment by zdenek-crha** [comment]
I would second the request to make color scheme configurable. I use terminal config with bright background and there are parts of the tui that are not only **hard to read**, but **impossible** to read:

![git-bug_ui_on_bright_bg](https://user-images.githubusercontent.com/35028759/93748708-fd65f480-fbf8-11ea-891f-cf54e022d955.png)

That black rectangle in the screenshot above contains text "No description provided.", but the only way to find that is to open `git-bug` in different terminal with dark background.

As for configuration, why not use `.gitconfig` to do that? I see following advantages:

* it is configuration file all git users know
* having config for all `git` related tools in one place is nice
* `git-bug` stores `git-bug.identity` in there so there should already be way to access it from code
* `git` has `color` section that could be used for *some* `git-bug` elements
* `git-bug.ui` section could store colors for elements missing from default `color`

**Comment by MichaelMure** [comment]
One thing that could be tried before thay is to always set both foreground and background color, and not use the "default" color.

**Comment by zdenek-crha** [comment]
@MichaelMure That could work.

The only thing I would be worried about is default terminal bg color  'leaking' in places and causing patches and artifacts in display. Fixing all those leaks may be more expensive than implementation of color scheme loading. But there is no way to know if that happens without trying it out.

**Comment by AtomToast** [comment]
I really like the first idea of zdenek. Foreground and background color aren't always reliable since for example in my colorscheme (monokai) both the foreground color and the blue are bright colors

**Comment by MichaelMure** [comment]
@AtomToast have you tried #457 ? Could you show what it looks like for you?

I'd be happy to have a way to configure those colors, I just don't have the bandwidth to take care of it. Now, another problem on the horizon is that access to git is being migrated to `go-git` instead of launching `git` CLI commands, and `go-git` does not read the global config file at all :-|

**Comment by MichaelMure** [comment]
Although it would be possible to still use the git CLI to read the global config. I guess I can live with that little mess.

**Comment by AtomToast** [comment]
![image](https://user-images.githubusercontent.com/27757087/93775814-65750480-fc12-11ea-8976-1eb272419b72.png)
as far as I can tell there is no difference for me in his branch. However from just randomly changing the `BlueBg` to `YellowBg` in `termui/help_bar.go` it already becomes much more readable. At least in my colorscheme.

![image](https://user-images.githubusercontent.com/27757087/93776508-209d9d80-fc13-11ea-9312-1cd2f994f492.png)

**Comment by MichaelMure** [comment]
#457 is merged, which should improve things a bit.

> Now, another problem on the horizon is that access to git is being migrated to `go-git` instead of launching `git` CLI commands, and `go-git` does not read the global config file at all :-|

This particular problem is fixed in #412 (soon to be merged) so it will still be possible to read the global config and thus implement a configurable color scheme.

**Comment by GlancingMind** [comment]
Wouldn't it be better to ship the terminal UI with a simple black and white color scheme (except for label)?
E.g. default terminal background and default terminal font color.
Then the colors should not conflict with the users terminal color scheme.
If preferred, the colors could still be changed with a configuration file or within the git config.

**Comment by MichaelMure** [comment]
Closing, please reopen if it's still a problem.
