### ISSUE TITLE
feat: webui - generate a static site

### ISSUE THREAD

**Issue by r14c** [MichaelMure/git-bug#454]
i would like to be able to export the webui as a static site. the go server is fine, but in some cases its just easier and better to have a bunch of static files on a webserver. i can understand if there is not interest in implementing this in core, but i thought i'd bring it up since i couldn't find a mention of this in the issues.

**Comment by MichaelMure** [comment]
You could built the webui from the source in https://github.com/MichaelMure/git-bug/tree/master/webui.

A problem you might have though is that the graphQL API is expected to be on the same server (same root, same port). That part will depend on how you setup things. If you are up for contributions, I'm willing to merge a PR that allow to configure the graphql endpoint.

**Comment by r14c** [comment]
no i mean a completely static export that doesn't rely on a web server for anything other than serving static files.
