### ISSUE TITLE
rm command doesn't exist

### ISSUE THREAD

**Issue by njjerrysmith** [MichaelMure/git-bug#461]
Just used brew to install git-bug 0.7.1 and like (https://github.com/MichaelMure/git-bug/pull/433#issuecomment-665019422) I made a test bug and went to delete it.

Found all the references to the command through the repo, but `commands` or `help` doesn't show the command. And trying to call it suggests `ls`.

<img width="1437" alt="Screen Shot 2020-10-04 at 2 45 00 PM" src="https://user-images.githubusercontent.com/98006/95025558-3322c880-0650-11eb-86c7-570842f15997.png">

**Comment by MichaelMure** [comment]
The `rm` command is in the unstable version but you will have to wait for a release to use it.

If it's a problem, you can remove the reference manually in `.git/refs/bugs/...`
