### ISSUE TITLE
feat: a command to list matching bug id from a prefix

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#47]
To be able to auto-complete bug id from a prefix, a hidden command to query the repo for matching id is necessary. 

`git bug ls-id [<prefix>]`

If no prefix is given, output all existing id.

**Comment by sladyn98** [comment]
This feature could be implemented by adding a new command in commands such as `list_id.go` and the implementation could be based off  the use of  `ListLocalIds` function in ```bugs/bug.go```.The prefix could be matched using a prefix match which would return the matching prefixes.
