### ISSUE TITLE
How do users submit bugs?

### ISSUE THREAD

**Issue by SoniEx2** [MichaelMure/git-bug#475]
When you put bugs in git, it's kinda hard to push them to someone else's repo. How does this project handle that?

**Comment by MichaelMure** [comment]
Please have a look at the workflow section in the readme. Let me know (and reopen) if that doesn't clear up things.

**Comment by SoniEx2** [comment]
It didn't. It seems like it's not supported?

Uh, do you think you could use something like @ganarchy to make it supported?

**Comment by MichaelMure** [comment]
If you are talking about people with git access, you can push/pull to a git remote you have access to. Most of the time you would use the same remote as you are using to collaborate on code.

If you are talking about people external to the project, the goal is to have the webui act as a portal with external authentication.

Isn't that enough?

**Comment by SoniEx2** [comment]
... not quite?

it's (still) too centralized.

**Comment by MichaelMure** [comment]
Every system made for people to interact will need some form of infrastructure. I believe that's not a problem on it's own as long as you can adapt that infrastructure and keep full control of your data.
Regarding git-bug, there is different ways to make it less reliant on ... git I suppose? git-bug could be combined with other initiatives to make git use IPFS or other decentralized data network. Or even remove entirely git from the picture. But one step at a time. Don't make perfect be the enemy of better.

**Comment by SoniEx2** [comment]
it'd be cool if this repo and this repo's issues were both on @ganarchy. you don't have to move the repo or anything, just create a simple commit. I've wanted to do something like this (federated issue tracker) with ganarchy anyway but wasn't sure how to do it, and building upon an existing framework/workflow/design (like your project) seems like a good idea?

**Comment by MichaelMure** [comment]
I can't say if that make sense, I don't understand what ganarchy is.

**Comment by SoniEx2** [comment]
GAnarchy is basically this: https://github.com/MichaelMure/git-bug/network

but with 3 key differences:

1. across websites/hosts
2. with no concept of an "upstream" repo
3. without javascript

and GAnarchy attempts to encourage users to use this for development, instead of the pull request model. you can still accept pull requests and email patches tho.
