### ISSUE TITLE
[gitlab] Adding bridge fails

### ISSUE THREAD

**Issue by nettnikl** [MichaelMure/git-bug#477]
I recently found this project and found it to be a perfect candidate to backup projects from a gitlab instance i will soon lose access to.
I've had unrelated problems with the latest release, so i chose to use the current git version.
But i found it hard to add the bridge authentification to the config in this version (In the release version this did work).

Release:
```
➜  project git:(master) ../../git-bug_linux_amd64 bridge configure -t gitlab -u gitlab.example.com/path/project -b https://gitlab.example.com/ -n default
Building identity cache... Done.
Building bug cache... Done.
Gitlab login: ^C

➜  project git:(master) ../../git-bug_linux_amd64 bridge configure -t gitlab -u gitlab.example.com/path/project -b https://gitlab.example.com/ -n default --token *****************
Identity d48fb1a created, set as current
Successfully configured bridge: default
```

Git version:
```
➜  project git:(master) git bug bridge configure -t gitlab -u https://gitlab.example.com/path/project -b https://gitlab.example.com/ --token ************** -n default
A lock file is present but the corresponding process is not, removing it.
Identity 97fb07e created, set as current
Successfully configured bridge: default
➜  project git:(master) git bug bridge pull
A lock file is present but the corresponding process is not, removing it.
Error: loading credential: no credential salt found
➜  project git:(master) git bug bridge auth
Error: loading credential: no credential salt found
```

I tried to reconstruct what went wrong, and i suspect that the call to `auth.List` in `config.promptTokenOptions` "throws" this error.
I managed to get the git version of git-bug working again by commenting out `return nil, err` and replacing it with continue at line 162,168 in auth.credentials.
But as this is just a very messy workaround - do you have any idea what causes this? Or should i try to find a real fix?

Disclaimer: I'm new to this project and also have *no* experience with golang.

**Comment by MichaelMure** [comment]
Hmm, when switching from the last release to master, did you use `git-bug-migration` ?

**Comment by MichaelMure** [comment]
If yes, it was likely https://github.com/MichaelMure/git-bug-migration/commit/e246349018619cec4245f84c8404e66aeb559d52

In that case, you can delete `~/.config/git-bug/keyring` (assuming linux, not so sure where it would be otherwise) and run the updated migration tool again.

**Comment by nettnikl** [comment]
Yes i did use `git-bug-migration`, and i am using linux. After deleting the files in the specified folder and reverting my changes, it did work as intended. Thank you very much for your help!
Should i report this as a bug in the migration tool then?

**Comment by MichaelMure** [comment]
Nah, it's fixed (and released) already. Thanks for the report :)
