### ISSUE TITLE
[gitlab] missing text cleanup for the title

### ISSUE THREAD

**Issue by nettnikl** [MichaelMure/git-bug#481]
When importing issues via `bridge pull`, git-bug performs a string validation on the title and the message.
As not all gitlab instances perform this kind of validation, not all issues possible in gitlab can be imported as git-bug bugs.

For example control characters like U+007F can be used in a gitlab issue title, but the import fails with the message `title is not fully printable`.

A possible workaround is to rename the issue.
I'm well aware this character should not be there and that would be the best solution, but i don't want to change the history of the legacy project in question.

To be able to import such projects, the introduction of a `-f, --force` or `--no-validation` flag for bridge pull could be considered.

**Comment by MichaelMure** [comment]
This should be pretty easy to fix. The gitlab bridge does cleanup the description of an issue but the same is missing for the title.

See https://github.com/MichaelMure/git-bug/blob/master/bridge/gitlab/import.go#L141
