### ISSUE TITLE
[github] Auth endpoint is being EOL november 13

### ISSUE THREAD

**Issue by joeytwiddle** [MichaelMure/git-bug#484]
I just tried git-bug today, and the github bridge helped set up authentication for a private repository. But I got this email, and it looks like bad news:

> On October 28th, 2020 at 15:24 (UTC) you or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent Go-http-client/1.1.
>
> We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication https://docs.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
>
> You can learn more about these changes by visiting our developer blog https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/

Sorry to be the bearer!

**Comment by MichaelMure** [comment]
Yeah, that's no fun.

My understanding is that git-bug need to implement the following flow: https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#device-flow

That seems doable with a limited scope of changes. Any takers?

**Comment by MichaelMure** [comment]
Current flow is over here: https://github.com/MichaelMure/git-bug/blob/master/bridge/github/config.go#L172-L366

**Comment by rng-dynamics** [comment]
I would like to take the issue. Don't expect me to finish the issue very fast, though.

**Comment by MichaelMure** [comment]
Yes please!

**Comment by rng-dynamics** [comment]
It seems like we need to have a **client_id** from Github in order to user their OAuth authorization (as described in https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#device-flow).

@MichaelMure: Do you have one?
If not, do you want to register an app for the git-bug organization as descirbed at https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-an-oauth-app ?

**Comment by MichaelMure** [comment]
I don't have one, but I'll make one.

**Comment by MichaelMure** [comment]
Any idea what I should have as Authorization callback URL ?

**Comment by MichaelMure** [comment]
Alright, I set that url to `http://example.com`. I believe it's not useful for the device flow. I also opted in for the device flow.

Client Id is `ce3600aa56c2e69f18a5`.

That said, you might want to create an app on your account while you develop that thing, so you can see what is hapenning.

**Comment by rng-dynamics** [comment]
Thanks

**Comment by MichaelMure** [comment]
Fixed with #496 :tada: .
The annoying thing though is that we can't release a new version at the moment.
