### ISSUE TITLE
Installation with `go get`

### ISSUE THREAD

**Issue by xloem** [MichaelMure/git-bug#487]
I'm not too familiar with go, but I know I can install most apps from source by typing `go get` and the github url or a subfolder.  It's surprising to me that this doesn't work for this project.

Was this a design decision, or is it missing functionality?

**Comment by MichaelMure** [comment]
What problem do you get? What go version?

**Comment by xloem** [comment]
```
$ go version
go version go1.15.2 linux/amd64
$ go get github.com/MichaelMure/git-bug
go/src/github.com/MichaelMure/git-bug/api/graphql/graph/gen_graph.go:22:2: cannot find package "github.com/vektah/gqlparser/ast" in any of:
        /usr/lib/golang/src/github.com/vektah/gqlparser/ast (from $GOROOT)
        /home/user/go/src/github.com/vektah/gqlparser/ast (from $GOPATH)
```

**Comment by MichaelMure** [comment]
Would that work with `GO111MODULE=on go get github.com/MichaelMure/git-bug` ?

Note though that you won't have a proper version backed in, as this is done in the makefile.

**Comment by xloem** [comment]
It installs fine with that environment variable set.  Thanks.  I'll let you close the issue if you consider that sufficient.
