### ISSUE TITLE
feature: basic pipe bridge

### ISSUE THREAD

**Issue by xloem** [MichaelMure/git-bug#489]
It would be nice to have an all-purpose cli bridge that accepts maybe http://ndjson.org/ or somesuch, for export and import of bugs, and so that users can write small special-purposes bridges in their familiar languages.

**Comment by xloem** [comment]
a bridge to https://github.com/driusan/bug (which follows https://github.com/driusan/PoormanIssueTracker ) or https://github.com/dspinellis/git-issue or somesuch might work here instead of pipes, too

**Comment by MichaelMure** [comment]
Could you detail a bit this idea? Not sure I follow.

If you are talking about a tool to transfer issues from say, github to gitlab, to me it would be outside of the git-bug scope. That said, it's possible as an external project can import git-bug as a library and just do that.

**Comment by xloem** [comment]
I'm looking for a way to import (possibly also export) the contents of a git-bug repository, from arbitrary new archive formats.  My use case at the moment is recovering github issues from the gharchive event logs, but it seemed the niche of making a general user interface for import or export was missing.  git has `git-fast-import` and `git-fast-export` for this.  They read or write to pipes in a way that anybody can write a script to interoperate with, to import or export repositories.

I've found it is less work for me to simply augment the shell commands to accept more arguments and output more data if requested,which basically accomplishes the same goal: the using script ends up running commands instead of writing to or reading from a pipe.

Does this make sense?

In the much longer term, if there were some simple general purpose pipe format, then making many projects interoperate can get much easier (consider git-issue, BugsEverywhere, git-ssb) because it comes down to getting them to support one import and export format, rather than writing bridges between every combination of pairs.

What do you think about small obscure use cases like gharchive import?

**Comment by xloem** [comment]
#501 appears to address the exporting half of this wonderfully.  Github ended up reopening the repository I was trying to recover from archive, so I no longer personally need this.  Closing since nobody else has requested it.
