### ISSUE TITLE
Enhanced shell completion

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#493]
Cobra, the library used to implement the CLI commands also generate the shell completion scripts, for bash, zsh, fish and powershell. This completion scripts are based on the description of each commands (living in https://github.com/MichaelMure/git-bug/tree/master/commands).

At the moment, those completion works decently, completing command names and flags. However it would be possible to do better. By teaching cobra (see https://github.com/spf13/cobra/blob/master/shell_completions.md#customizing-completions) about what is expected, it should be possible to:
- disable the default completion showing files when it's not appropriate
- complete based on git-bug specific terms (`git bug ls [tab][tab]` would also complete with [query qualifiers](https://github.com/MichaelMure/git-bug/blob/master/doc/queries.md))
- complete based on git-bug specific data (`git bug show [tab][tab]` would complete with bug Ids, possibly with the bug title)

**Comment by Ogguz** [comment]
I want to work on this

**Comment by MichaelMure** [comment]
Yes please!

**Comment by krobelus** [comment]
As a first step, I have added bug ID completions. They work well in fish, I'm not sure how to make completions work in zsh.

**Comment by TheNerdyHamster** [comment]
What is the status on this issue?
I would be interested to continue on it, if its not completed
