### ISSUE TITLE
Serialization format 

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#5]
Bug's data are stored using git `Commit`, `Tree` and `Blob`. Inside a `Blob` is serialized an `OperationPack`, that is an array of edit operation on the bug's state.

This `OperationPack` is currently serialized using golang's [gob](https://golang.org/pkg/encoding/gob/), which is neat because it just works. However, it might not be the best option for interoperability with other tools in the future.

How should that be serialized ? Json ? In any case, git will compress the data using zlib so a text format might not be that terrible.

Feel free to argue a case here.

**Comment by daurnimator** [comment]
I just found the project via hackernews. I'd love to give this sort of thing a try, and integrate it into other tools. However using go serialisation rules out all my languages of choice.

I'd say use something JSON based, or if that's not enough, [CBOR](http://cbor.io/).

**Comment by MichaelMure** [comment]
For the record, it would be an easy change to use something else, it's only a few lines of code: https://github.com/MichaelMure/git-bug/blob/d959acc29dcbc467790ae87389f9569bb830c8c6/bug/operation_pack.go#L25-L52

**Comment by lukechampine** [comment]
My two cents: `gob` is convenient and efficient, but not a great choice if you want interop with other languages. Unfortunately there just aren't many binary formats that are widely supported, except perhaps protobufs.

JSON is probably your best bet. As you noted, it will be compressed anyway, and if performance is an issue you can always switch to a faster JSON encoder. The only big downside to JSON that I'm aware of is poor support for encoding binary blobs (`encoding/json` encodes `[]byte` as a base-64 string). But if `OperationPack` is almost entirely textual data anyway, there's little reason to worry about that.

**Comment by avar** [comment]
Git does its own delta-compression on top of zlib. You should decide this using a combination of whatever format needs you have (can you add more fields, is it extensible etc.), and how git manages to compress this using both delta compression and zlib, which you can figure out using a large enough set of realistic test data.

**Comment by MichaelMure** [comment]
To give more details about the requirement, OperationPack hold currently very simple data (string, int, array..), and it's likely to stay the same even when adding new operations. For instance, embedded files are stored in git blobs and then linked in the git tree.

The only tricky part is that an OperationPack is an mixed array of Operation so the decoder need to support that and match the correct go struct for each operation.

**Comment by j-f1** [comment]
[MessagePack](https://msgpack.org/) is another option, but I feel like MessagePack and CBOR are both designed for getting the smallest possible representation of data, whereas JSON is designed to be human-readable, ASCII-compatible, and simple to parse. Compare [JSON’s spec](https://json.org/) (the sidebar) with the [CBOR](https://github.com/cbor/spec-with-errata-fixed/blob/master/rfc7049-errata-corrected.txt) and [MessagePack](https://github.com/msgpack/msgpack/blob/master/spec.md) specs.

**Comment by avar** [comment]
@MichaelMure This test case really isn't meaningful. You're just testing how a given payload compresses with zlib when creating loose objects, since when you add a new object it's compressed, a header is added to it, and it's added to the object store.

Instead, you should after every addition do `git add && git commit && git gc`. Then measure the total size of the now-packed .git/objects directory, not individual objects.

At that point, these objects will be delta-compressed, so you can see how the size of the repo grows as they're added.

The size of individual objects is pretty much irrelevant. You can have 10 objects that are all 1GB, but delta-compress down to 1GB + 1MB or whatever, or 10GB if they don't delta-compress at all.

**Comment by avar** [comment]
@MichaelMure Also in reply to:

> Who knows how the git compression behave on something that is already binary.

I'm sure there's some obscure edge case where the compression is tweaked for textual content in some way that'll prove me wrong, but in general this doesn't matter at all.

Git's just as good at delta-compressing binary data and non-binary data. What it's not good at compressing (and this goes for any compression), is data that's wildly different from one object to the next.

It just so happens that *generally* binary data is less delta-compressible, think say two *.mp3s with different songs v.s. a *.txt change to its lyrics.

But for these sort of pack formats I wouldn't expect them to delta-compress any worse than say JSON. It's going to be other things that matter, e.g. let's say you use a JSON encoder  where the keys of the payload aren't sorted, and thus are different every time, that'll compress worse than if they're sorted, same for doing the same in some binary key-value format.

I do think that for UI purposes it makes sense to pick a widely implemented & used text format like JSON for introspection purposes and the availability of tooling (e.g. `jq`), if the compression numbers for it aren't much worse that is.

**Comment by MichaelMure** [comment]
That's a good point, I'll check the repo size as well, before and after a `git gc`.

**Comment by MichaelMure** [comment]
Alright, another run with the size of the repo before and after a `git gc` (initial empty size substracted), 1000 OperationPack serialized:

```
GOB
Creating repo: /tmp/272689118
raw: 4446, git: 1944, ratio: 43.724697%
raw: 4774, git: 2075, ratio: 43.4646%
raw: 5075, git: 2203, ratio: 43.408867%
raw: 4135, git: 1795, ratio: 43.409916%
raw: 5901, git: 2437, ratio: 41.298084%
raw: 2919, git: 1372, ratio: 47.0024%
raw: 4974, git: 2098, ratio: 42.179333%
raw: 5074, git: 2153, ratio: 42.432007%
raw: 3600, git: 1613, ratio: 44.805557%
raw: 4663, git: 2016, ratio: 43.23397%
...
Unpacked: 1926463
GC packed: 1926510
Packing diff: 47
GC packed aggressive: 1926510
Packing diff: 0

JSON
Creating repo: /tmp/263735205
raw: 4094, git: 1706, ratio: 41.67074%
raw: 4428, git: 1837, ratio: 41.485996%
raw: 4731, git: 1968, ratio: 41.597973%
raw: 3776, git: 1547, ratio: 40.96928%
raw: 5554, git: 2192, ratio: 39.467052%
raw: 2566, git: 1136, ratio: 44.27124%
raw: 4628, git: 1863, ratio: 40.254967%
raw: 4732, git: 1921, ratio: 40.595943%
raw: 3242, git: 1377, ratio: 42.47378%
raw: 4320, git: 1773, ratio: 41.041668%
...
Unpacked: 1687200
GC packed: 1687247
Packing diff: 47
GC packed aggressive: 1687247
Packing diff: 0

CBOR
Creating repo: /tmp/701783232
raw: 3984, git: 1705, ratio: 42.796185%
raw: 4311, git: 1838, ratio: 42.63512%
raw: 4613, git: 1965, ratio: 42.597008%
raw: 3674, git: 1550, ratio: 42.18835%
raw: 5438, git: 2192, ratio: 40.308937%
raw: 2462, git: 1134, ratio: 46.060116%
raw: 4514, git: 1863, ratio: 41.2716%
raw: 4613, git: 1916, ratio: 41.534794%
raw: 3137, git: 1376, ratio: 43.863564%
raw: 4202, git: 1766, ratio: 42.027603%
...
Unpacked: 1685158
GC packed: 1685205
Packing diff: 47
GC packed aggressive: 1685205
Packing diff: 0

MsgPack
Creating repo: /tmp/132917535
raw: 3984, git: 1723, ratio: 43.247993%
raw: 4310, git: 1854, ratio: 43.01624%
raw: 4611, git: 1985, ratio: 43.049232%
raw: 3672, git: 1562, ratio: 42.538128%
raw: 5436, git: 2204, ratio: 40.544518%
raw: 2460, git: 1152, ratio: 46.82927%
raw: 4512, git: 1875, ratio: 41.55585%
raw: 4614, git: 1932, ratio: 41.872562%
raw: 3138, git: 1395, ratio: 44.455067%
raw: 4202, git: 1783, ratio: 42.432175%
...
Unpacked: 1700178
GC packed: 1700225
Packing diff: 47
GC packed aggressive: 1700225
Packing diff: 0
```

Whatever the format, there is no compression taking advantage of the similarity between each OperationPack. The packed repo is actually bigger by 47 bytes, and a `git gc --agressive` does nothing.

**Comment by j-f1** [comment]
Interesting that JSON and CBOR end up almost the same size.

**Comment by avar** [comment]
In a lot of cases --aggressive does nothing, since e.g. if you have files that keep growing they'll already be in the --window and --depth described in the git-repack manpage, --aggressive just tweaks those values from the default of 10/50 to 250/50. I wouldn't be surprised if for such an artificial testcase you got simliar/the same results with --window=1 --depth=1 or whatever.

Is the history this go tool produces accessible somewhere?

**Comment by MichaelMure** [comment]
Each OperationPack are independent, the similarities would be between them would be only the serialization format structure. There is no file growing.

It's not that surprising that git doesn't compress that.

> Is the history this go tool produces accessible somewhere?

I'm not sure it answer your question, but have a look at https://github.com/MichaelMure/git-bug/blob/master/doc/model.md.

**Comment by avar** [comment]
I mean you're producing some git data during the benchmark in a repo, is
the result available somewhere? I could run it myself, but then I have to
figure out how to run/install go etc.

**Comment by MichaelMure** [comment]
@avar These blobs are not tied up in a branch, it's rather impractical to push that somewhere.
Please install go (probably just a package), checkout the branch and run `go run misc/serial_format_research/main.go`.

**Comment by MichaelMure** [comment]
With no sign of troubles after various tests, let's consider the matter resolved :-)

**Comment by andyl** [comment]
Is there a CLI command to generate a JSON dump from the issues?

**Comment by MichaelMure** [comment]
@andyl there is not. What's your usecase ?

**Comment by andyl** [comment]
@MichaelMure I'm working on a project that allows people to post auction-style bids for issues (see bugmark.net).  We'd very much like to integrate with git-bug.  To do this, we need to be able to poll the issue repository and grab a json-like representation.  JSON would be simple for us, but if there is another way to integrate open to that too.

**Comment by MichaelMure** [comment]
@andyl that's certainly doable and should be supported by the CLI tools.

Could you open a new issue where we can discuss that ?

**Comment by andyl** [comment]
> Could you open a new issue where we can discuss that ?

@MichaelMure see #45
