### ISSUE TITLE
'Error: strconv.Atoi: parsing "": invalid syntax' after running out of space

### ISSUE THREAD

**Issue by krisfris** [MichaelMure/git-bug#527]
Just ran out of hard drive space, tried running `git bug add` and now it returns this error for every command even though I freed up enough space.

```
Error: strconv.Atoi: parsing "": invalid syntax
```

Is there a way to recover?

**Comment by MichaelMure** [comment]
There is not much of those `strconv.Atoi` in the code base. I'd say you have a broken lock file (`.git/git-bug/lock`) or a broken git config.

**Comment by krisfris** [comment]
You're right, after I deleted `.git/git-bug/lock` it's working again. It was an empty file. Thanks!
