### ISSUE TITLE
CLI - Little spelling mistake is shown in the console when git-bug.exe is executed without args

### ISSUE THREAD

**Issue by claudioantonio** [MichaelMure/git-bug#528]
See the red balloon in the attached image.
The correct word would be YOU instead of YOUR, isn´t it?
At the end of the same paragraph PEOPLES should be PEOPLE.

![little spelling mistake](https://user-images.githubusercontent.com/12503122/105558794-35d42700-5cee-11eb-971b-a2c3492748bc.png)

**Comment by claudioantonio** [comment]
I tried to define labels (CLI, questions) but they were disabled to me.

**Comment by MichaelMure** [comment]
I think you are correct. Can you open a PR?

**Comment by MichaelMure** [comment]
Actually it seems that you were using a quite old version. This is already fixed in master.

**Comment by claudioantonio** [comment]
@MichaelMure I used the binary for 0.7.1 release.
