### ISSUE TITLE
CLI - When user runs git-bug in a repo without an identity set, the orientation message can cause confusion

### ISSUE THREAD

**Issue by claudioantonio** [MichaelMure/git-bug#529]
The orientation message could be:
> To interact with bugs, an identity first needs to be created using "**git-bug** user create"

Instead of:
> To interact with bugs, an identity first needs to be created using "**git bug** user create"

This can avoid a first interpretation that a git command must be executed. I swear a did not think it but... :-)
![termui](https://user-images.githubusercontent.com/12503122/105560736-75514200-5cf3-11eb-8cee-20525e63853f.png)

**Comment by MichaelMure** [comment]
Hmm I dunno. I believe it's better to be consistent than slightly misleading in this case. All the documentation is written based on the idea that git-bug integrate with git as a subcommand, that is `git bug ....`.

I've been thinking about dropping out of that system and rename the binary into `gb` (see https://gitter.im/the-git-bug/Lobby?at=5fa13ba92a35440715011eb8) but we are not there yet.

**Comment by MichaelMure** [comment]
This will get resolved when the dilemma between integrating as a git subcommand vs a standalone binary get resolved. Closing.
