### ISSUE TITLE
WebUI - Allow to change a bug title

### ISSUE THREAD

**Issue by claudioantonio** [MichaelMure/git-bug#535]
Today when We select a bug It´s only possible to add comments but in the same page should be possible to change bug title too.

**Comment by claudioantonio** [comment]
Once user select a bug, the details page will be presented and a new button "Edit" will be visible
![image](https://user-images.githubusercontent.com/12503122/106597534-534a9180-6535-11eb-9732-18e21ab946e6.png)

When We click on Edit button, the bug title become editable and two buttons appear: Save and Cancel
![image](https://user-images.githubusercontent.com/12503122/106597668-7b39f500-6535-11eb-94a8-9476efaf2c38.png)

Click on Save will change bug title and the timeline will be refreshed
![image](https://user-images.githubusercontent.com/12503122/106597741-9b69b400-6535-11eb-9841-2dcccc724b33.png)

**Comment by claudioantonio** [comment]
@MichaelMure 2 questions:

1. Does the screenshots look good for You?
2. In the detail page Do You expect a new issue button like github?

**Comment by MichaelMure** [comment]
1. Looks good to me. Buttons are maybe a bit big / too visible?
2. Yeah, that'd be nice.

**Comment by claudioantonio** [comment]
1. Ok, I fixed to size=small. ;-)
![image](https://user-images.githubusercontent.com/12503122/106642420-16978e00-6567-11eb-8517-0e01a7b92648.png)


2. I created an issue for it.
