### ISSUE TITLE
WebUI - Change button "Comment" style in the bug details page

### ISSUE THREAD

**Issue by claudioantonio** [MichaelMure/git-bug#539]
Button must be green like "New issue" and "Submit new issue" buttons.

**Comment by claudioantonio** [comment]
@MichaelMure I think this issue can be closed. ;-)

**Comment by MichaelMure** [comment]
FYI, in your PRs your can comment with `fix #539` so that the issue is closed automatically when merged.

**Comment by claudioantonio** [comment]
Thank You for the advice! I will pay attention to that next time. ;-)
