### ISSUE TITLE
Identity management

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#55]
Currently, each `Operation` store the author independently. While it's easier and works well for now, there is some shortcoming:

- no way to update an identity (update an email, update an avatar ...)
- no easy way to recognize that two author are the same
- data is stored multiple time (no that much of an issue with the git compression)
- crypto signature & authorization scheme is hard to implement

So I've been thinking it could be changed for the following (rough idea):

- identity (including a public key would be neat) is stored as a JSON in a git blob
- this blob hash give the `id` for this identity
- each time an identity is updated, a new blob is created with the new values and these blob are linked together in a chain of commit, the head being the last state.
- in each operations, actor(s) are simply identified with the id.

Now, I'm not sure yet how these identities should be stored and distributed. a git ref for each identity ? Each required identity linked in the `OperationPack` git tree ? A master ref aggregating all known identities ?

Hopefully this would be the last of the backward-incompatible change in the data model

**Comment by MichaelMure** [comment]
Here is the CLI UX I thought about, comments ?

```markdown
# Display current identity (any identity if <id> is specified)
git bug id [<id>] [<time>]

# Display the current name (any identity if <id> is specified)
git bug id name [<id>] [<time>]

# Display the current email (any identity if <id> is specified)
git bug id email [<id>] [<time>]

# Display the current login (any identity if <id> is specified)
git bug id login [<id>] [<time>]

# Display the current avatarURL (any identity if <id> is specified)
git bug id avatarURL [<id>] [<time>]

# Set the current name
git bug id set name <name>

# Set the current email
git bug id set email <email>

# Set the current login
git bug id set login <login>

# Set the current avatarURL
git bug id set avatarURL <avatarURL>

# Display the current keys (any identity if <id> is specified)
git bug keys [<id>] [<time>]

# Manage keys (to be determined)
git bug keys import ...
git bug keys export ...
git bug keys add ...
git bug keys generate ...
git bug keys revoke ...
```

**Comment by MichaelMure** [comment]
#89 has been merged with the bulk of the changes, but there is a few things left to iron properly before a release can happen.

**Comment by MichaelMure** [comment]
As of now, this is pretty much done. All the core features are there, tested and working.

What is left is the few command line tool to get/set particular identity fields:

```
# Display the current name (any identity if <id> is specified)
git bug user name [--time <time>] [<id>]

# Display the current email (any identity if <id> is specified)
git bug user email [--time <time>] [<id>]

# Display the current login (any identity if <id> is specified)
git bug user login [--time <time>] [<id>]

# Display the current avatarURL (any identity if <id> is specified)
git bug user avatarURL [--time <time>] [<id>]

# Set the current name
git bug user set name <name>

# Set the current email
git bug user set email <email>

# Set the current login
git bug user set login <login>

# Set the current avatarURL
git bug user set avatarURL <avatarURL>
```

**Comment by edef1c** [comment]
Is there an intention to allow adopting a bridge identity that has otherwise not interacted with the particular repository? This comment is partially a way of allowing me to adopt my GitHub identity for this repo, because I'm not sure if I can merge the two if I use the exporter — I certainly couldn't figure out how to add new information to an existing identity.

**Comment by hoijui** [comment]
in a fully distributed git world, this is a more important and difficult question...
how do we prevent identity theft?
should measures preventing that be the default or optional?
would each user decide whether they want to use a secure way of identity management, or each repo, or a mix/combination of the two?
is avatar-URL really enough, or should the avatar image rather (optionally) be stored in the repo?
...

I feel like such decisions are really hard, and in the end will always have to be changed later on, as one did not think of everything from the start, so the most important thing in my eyes, is to use versioning, and in such a way that really everything can be changed, if deemed necessary, or even just beneficial.

what is the _login_ used for?

**Comment by hoijui** [comment]
just stumbled over W3Cs [Decentralized Identifiers (DIDs)](https://www.w3.org/TR/2019/WD-did-core-20191209/):

> Decentralized identifiers (DIDs) are a new type of identifier to provide verifiable, decentralized digital identity. These new identifiers are designed to enable the controller of a DID to prove control over it and to be implemented independently of any centralized registry, identity provider, or certificate authority. DIDs are URLs that relate a DID subject to a DID document allowing trustable interactions with that subject.

it sounds quite optimal so far. It is still in the making though (as of mid 2020)!

**Comment by MichaelMure** [comment]
> in a fully distributed git world, this is a more important and difficult question...
> how do we prevent identity theft?

By having crypto keys. See https://github.com/MichaelMure/git-bug/issues/130

> should measures preventing that be the default or optional?
> would each user decide whether they want to use a secure way of identity management, or each repo, or a mix/combination of the two?

My view is that as a general UX principle git-bug should have a default that is 1) functional with little to no configuration 2) address a wide range of use cases and 3) allow to add additional constraint to restrict to a more specific use case.

For this problem in particular, I think the best way would be:
- default would have no crypto keys. Identity theft is possible but that's not a problem in a lot of real life scenario (you would first need to have git write access). Identities are marked as "unprotected".
- it's possible for each user to opt-in and protect their identity by adding keys
- when a project config exist, add a settings to enforce having keys for each identities

> is avatar-URL really enough, or should the avatar image rather (optionally) be stored in the repo?

It's very crude at the moment. Yes, it should be improved and stored in the repo if possible.

> I feel like such decisions are really hard, and in the end will always have to be changed later on, as one did not think of everything from the start, so the most important thing in my eyes, is to use versioning, and in such a way that really everything can be changed, if deemed necessary, or even just beneficial.

If by versioning you mean data model versioning, it's already there. Every piece of data stored in git has this version number. It's especially important because those are immutable. It's not really used though at the moment.

> what is the _login_ used for?

An identity's login is optional and is only meant to store the login used on the bridge that created this identity. It's just informational, to display in the UI both full name and login when available. This exist in part because Github mainly display the login (so you know people by that name) so if you don't have the login in git-bug's UI you can see names you have never seen before even though you know the people.

**Comment by MichaelMure** [comment]
Not super knowledgeable about DID but AFAIK they don't work offline ?

Note that identities in git-bug is just an interface (https://github.com/MichaelMure/git-bug/blob/master/identity/interface.go). It could be replaced by another implementation someday if the need arise.

**Comment by MichaelMure** [comment]
Closing as it's either done, outdated or non-actionable.
