### ISSUE TITLE
WebUI - update npm dependencies

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#552]
@claudioantonio could you update the NPM dependencies ? As you may have seen in the open PRs, some packages are outdated and have security issues (see #517, #520, #536).

**Comment by claudioantonio** [comment]
Yes, @MichaelMure .

**Comment by claudioantonio** [comment]
Pull requests #517 and #536 were merged.
I will test #520 asap.

**Comment by claudioantonio** [comment]
I merged PR #520 to current master locally and tested all webui features. I had no conflicts nor feature problems.
However, github checks indicate that this PR break some tests for  build (1.13.x, macos-latest) that are not related to webui as show below.

Can I approve this PR?

--------------------------------------------------------------------------------------------------------------------

=== RUN   TestPushPull
Building identity cache... Done.
Building bug cache... Done.
created repository git-bug-test-github-exporter-uxseSVSu
deleted repository: git-bug-test-github-exporter-uxseSVSu
--- FAIL: TestPushPull (2.76s)
    export_test.go:206: 
        	Error Trace:	export_test.go:206
        	Error:      	Received unexpected error:
        	            	was submitted too quickly
        	            	exporting github issue
        	            	github.com/MichaelMure/git-bug/bridge/github.(*githubExporter).exportBug
        	            		/Users/runner/work/git-bug/git-bug/bridge/github/export.go:255
        	            	github.com/MichaelMure/git-bug/bridge/github.(*githubExporter).ExportAll.func1
        	            		/Users/runner/work/git-bug/git-bug/bridge/github/export.go:183
        	            	runtime.goexit
        	            		/Users/runner/hostedtoolcache/go/1.13.15/x64/src/runtime/asm_amd64.s:1357
        	Test:       	TestPushPull

----------------------------------------------------------------------------------------------------------------

=== RUN   TestPersistedClock
--- PASS: TestPersistedClock (0.00s)
PASS
ok  	github.com/MichaelMure/git-bug/util/lamport	0.093s
?   	github.com/MichaelMure/git-bug/util/process	[no test files]
?   	github.com/MichaelMure/git-bug/util/text	[no test files]
?   	github.com/MichaelMure/git-bug/util/timestamp	[no test files]
?   	github.com/MichaelMure/git-bug/webui	[no test files]

**Comment by MichaelMure** [comment]
This is the CI for the github bridge that has some trouble with github's rate limiting. This is safe to ignore for now, hopefully we can have a better bridge that deal graciously with that.

I merged #520, which conclude that issue. Thanks!
