### ISSUE TITLE
Error importing from github

### ISSUE THREAD

**Issue by bqv** [MichaelMure/git-bug#561]
While trying to run bridge pull from github (nixos/nixpkgs)

Was told to include 8450:E73D:288B4F3:2CF6477:6022B965 when reporting.

Seemed to import a few issues and comments the first time, repeated attempts imported nothing and yield the same error.

**Comment by bqv** [comment]
N.b. this was just me testing if #315 was still an issue

**Comment by MichaelMure** [comment]
Well, is it? ;-)

**Comment by bqv** [comment]
Unclear, because I hit this bug :p

**Comment by MichaelMure** [comment]
Let's close as it's not actually a bug.

**Comment by bqv** [comment]
What does the code mean? I was unclear on what I'm reporting

**Comment by MichaelMure** [comment]
I have no idea what that code is ¯\\\_(ツ)_/¯

**Comment by rng-dynamics** [comment]
> What does the code mean? I was unclear on what I'm reporting

I believe the error code originates from the Github API. It's not a rate limiting error but an internal error of the github API. I have experienced similar errors when submitting "very big single queries". I am surprised that you get this error with the current implementation.

**Comment by bqv** [comment]
I suppose that's somewhat self explanatory

**Comment by rng-dynamics** [comment]
Just some additional information: The current implementation of the git-bug bridge uses many small GraphQL queries to the Github API. I did not have this error when I tried to pull the issues from nixos/nixpkgs but instead a simple rate limiting error.
