### ISSUE TITLE
git bug push fails

### ISSUE THREAD

**Issue by jkozak** [MichaelMure/git-bug#572]
I  have a repository without a branch called ```master``` (or ```main```) and attempts to ```git bug push``` fail.

I built ```git-bug``` from source on debian testing.

```
bisou:~/XXX$ git push origin
Everything up-to-date
bisou:~/XXX$ git bug push origin                                                                   
A lock file is present but the corresponding process is not, removing it.
Error: repository not found
```

If I set up a toy repo with remote bug pushing works.

**Comment by MichaelMure** [comment]
`git-bug` really shouldn't care what your main branch is called. In fact you can even use without any branches.

So the problem has probably a different origin. Are your git remote setup properly?

**Comment by jkozak** [comment]
Michael Muré writes:

> `git-bug` really shouldn't care what your main branch is called. In
> fact you can even use without any branches.
>
> So the problem has probably a different origin. Are your git remote setup properly?

I believe so, I've been using this repo and its remotes for some months.
I included an undramatic terminal capture of ```git push``` working.

--
John

**Comment by firecat53** [comment]
I'm seeing a similar problem:

    firecat53@scotty:~/docs/family/scott/src/projects/urlscan (develop) $ git push origin develop
    Everything up-to-date
    urlscan $ git bug push
    Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
    urlscan $ git bug push
    A lock file is present but the corresponding process is not, removing it.
    Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
    urlscan $ git bug pull
    Fetching remote ...
    Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

The lock file error appears after the initial failed attempt. From the git-bug tui, the 'pull' command pops up 'done' even though it appears to fail on the command line.

.git/config snippet for this repo:

    [remote "origin"]
        fetch = +refs/heads/*:refs/remotes/origin/*
        url = github:firecat53/urlscan.git
        gh-resolved = base
    [branch "develop"]
        remote = origin
        merge = refs/heads/develop
    [git-bug]
        identity = xxxxxxxxxxxxxxxxxxxxxx
    [git-bug "bridge.default"]
            target = github
            owner = firecat53
            project = urlscan
            default-login = firecat53
            lastImportTime = 1615736962

and the ~/.ssh/config snippet for `github` in the .git/config url:

    Host github
    User git
    Hostname github.com
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/xxxxxxx
    ControlPersist 10m
    ControlMaster auto
    ControlPath ~/.ssh/socket-%r@%h:%p

**Comment by MichaelMure** [comment]
Probably due to https://github.com/go-git/go-git/issues/218 or https://github.com/go-git/go-git/issues/143

**Comment by abdellatif-dev** [comment]
if you are on arch linux use git-bug-bin from the aur

**Comment by MichaelMure** [comment]
Closing as it's a quite old issue. Please reopen if it's still a problem.

**Comment by Subfortytwo** [comment]
Hi,
I am reopening the issue, since I am having the same with the version 0.8.0 of git-bug.
To me, it looks like the ssh config file is ignored:

```
$ git bug pull
13:16:57.712053 git.c:748               trace: exec: git-bug pull
13:16:57.712081 run-command.c:661       trace: run_command: git-bug pull
Fetching remote ...
Error: unknown error: 13:16:57.734930 git.c:462               trace: built-in: git upload-pack mysite:myproject

```

`mysite` is defined in `~/.ssh/config`

As a workaround, one should defined the ssh connection without any config alias, and also the **absolute path** for `myproject` (couldn't get relative path to work):
```
cat .git/config
[remote "origin"]
ssh://git@myipordomain:22222/home/git/myproject
fetch = +refs/heads/*:refs/remotes/origin/*
```
By doing this, I am finally able to `git bug pull/push`.
To me, it looks like it's a golang problem, but I don't have any knowledge in that language.
