### ISSUE TITLE
WebUI - Enable dark mode visualization

### ISSUE THREAD

**Issue by claudioantonio** [MichaelMure/git-bug#573]
Nowadays many apps offer a dark mode visualization for its GUI.

**Comment by GlancingMind** [comment]
@MichaelMure @claudioantonio Hi, I've got a working dark-mode. 
I still have to port this changes to upstream, but I thought you might like to see a [preview](https://github.com/GlancingMind/git-bug/pull/23#issuecomment-789667207). ;-)

**Comment by claudioantonio** [comment]
Hey @GlancingMind , congrats! Looks nice!
