### ISSUE TITLE
CLI - allow to use "user create" without prompt

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#577]
Similarly as `bridge configure`, `user create` should be possible to use purely with CLI flags, without interactive prompt.

**Comment by cvhariharan** [comment]
Hello @MichaelMure, if this issue is still open, I would like to give it a Go! 
From what I understand, when creating a user, instead of an interactive prompt to enter name, email this PR would replace that with flags.

**Comment by MichaelMure** [comment]
@cvhariharan yes please!

The command need to support both workflow: with flags and without flags (interactive prompt). So something like that: https://github.com/MichaelMure/git-bug/blob/master/commands/bridge_configure.go#L139-L151

**Comment by cvhariharan** [comment]
Will do :+1:
