### ISSUE TITLE
webui: Emoji support

### ISSUE THREAD

**Issue by pawamoy** [MichaelMure/git-bug#579]
Currently emojis in the webui are rendered as `:expressionless:`. It would be nice to render the actual emojis :slightly_smiling_face: 
I'm not sure how Markdown is rendered in the webui. Maybe a javascript lib could do the trick.

**Comment by MichaelMure** [comment]
Same as for https://github.com/MichaelMure/git-bug/issues/580#issuecomment-787517962, this looks doable with a remark plugin. Maybe https://github.com/remarkjs/remark-gemoji (from a quick browsing).

**Comment by GlancingMind** [comment]
I added emoji support within this PR. https://github.com/GlancingMind/git-bug/pull/44
![image](https://user-images.githubusercontent.com/9444609/113200679-ef102980-9268-11eb-83eb-aa8f849f2771.png)
