### ISSUE TITLE
WebUI - Refactoring label presentation to use material-ui´s Chip component instead of a styled span

### ISSUE THREAD

**Issue by claudioantonio** [MichaelMure/git-bug#586]
This is a first step to #575 .
Besides that, the Chip component offers more possibilities to enrich label interaction (for example, remove icon).

**Comment by timbkr** [comment]
Hi im also working on this
![labels](https://user-images.githubusercontent.com/76536085/110138403-3cb48600-7dd2-11eb-9b45-76f188a67000.jpg)
But still in very early stage. I have to get familiar with the project at first, just to let you know.

https://github.com/GlancingMind/git-bug/issues/8

**Comment by claudioantonio** [comment]
Hey @timbkr ! Thank You for the advice! I did a code and was trying to pass margin styles as param to the chip component from the Bug page. Go ahead!

On tip: try to use display flex, row direction, with space between elements and allow wrap. 😉 

![image](https://user-images.githubusercontent.com/12503122/110207254-007c3680-7e61-11eb-9b89-f5dae7573498.png)
