### ISSUE TITLE
Github bridge import: performing `bridge pull` several times does not consider the time when the last pull has been performed

### ISSUE THREAD

**Issue by rng-dynamics** [MichaelMure/git-bug#607]
I am importing all the issues from https://github.com/MichaelMure/git-bug .
```
$ ./git-bug bridge pull
[...]
imported 228 issues and 154 identities with default bridge
```

Then I execute the same command again (just this time with `time`). This takes much more time than it should:
```
$ time ./git-bug bridge pull
Building identity cache... Done.
Building bug cache... Done.
imported 0 issues and 0 identities with default bridge

real	5m52.578s
user	0m5.067s
sys	0m3.693s
```

git-bug actually queries all the issues from github eventhough it should not do that by using the `since` variable:
https://github.com/MichaelMure/git-bug/blob/fb6b2d873e1bbc653aa84ddce56c842202e00c33/bridge/github/import.go#L55
If I print the `since` variable in this situation I see the value ` 0001-01-01 00:00:00 +0000 UTC`.

On the other hand, using the `--since` command line argument does work and only issues starting from that date are queried from github (e.g.,  `git-bug bridge pull --since "27 March 2021"` does what one expects it to do).

**Comment by MichaelMure** [comment]
That looks like an issue when write/reading the value in the git config. I'll have to dig further.

**Comment by MichaelMure** [comment]
Alright so this was indeed multiple issues with the config read/write. https://github.com/MichaelMure/git-bug/pull/608 should fix that.
