### ISSUE TITLE
Editing comments (in TermUI and WebUI) has no effect

### ISSUE THREAD

**Issue by GlancingMind** [MichaelMure/git-bug#653]
The error seem to be introduced with this commit: https://github.com/MichaelMure/git-bug/commit/24155156223595e48f215e87cf9ce7895e22f4a7

**Comment by GlancingMind** [comment]
Reverting [this line](https://github.com/MichaelMure/git-bug/blob/master/bug/op_edit_comment.go#L38) back to `commentId = op.target` seems to fix the issue. But I'm not sure if this is the right way to solve the problem. [This discussion](https://github.com/MichaelMure/git-bug/pull/631#pullrequestreview-635388561)  seems to be related, maybe reverting the line was just forgotten?

**Comment by MichaelMure** [comment]
https://github.com/MichaelMure/git-bug/commit/24155156223595e48f215e87cf9ce7895e22f4a7 was correct. The problem is that there is a conversion missing.

EditCommentOperation correctly use an Operation's Id as the target. The problem is that the termui (and webUI I suppose) is using a comment's ID (a combined ID) directly without conversion. Where exactly this conversion should happen, I'm not so sure.

Also, having a different type (`entity.CombinedId`) might make sense to avoid those class of bugs. We would know what kind of Id we have and the compiler could enforce the correct usage.

**Comment by GlancingMind** [comment]
Tough problem. I added a CombinedId type and adjusted the function signatures accordingly.
But one Problem persists. The TimeLineItem interface requires an Id, but the CommentTimeLineItem uses a CombinedId, as it should match the Comment.Id (of type CombinedId).

**Comment by rng-dynamics** [comment]
> Also, having a different type (entity.CombinedId) might make sense to avoid those class of bugs. We would know what kind of Id we have and the compiler could enforce the correct usage.

If that works without introducing other complications, then that would help a lot, I guess.

**Comment by rng-dynamics** [comment]
If it where up to me I would aim for separate types for different kinds of Ids. But in case that does not work out as expected, one can add a field `plainId` to the `Comment` struct to store both Ids for each `Comment`. Then one has both Ids at his disposal.

**Comment by MichaelMure** [comment]
FYI I started working on that in https://github.com/MichaelMure/git-bug/pull/664 by having a dedicated `CombinedId` type and use that in various places, but I'm yet to figure out the clean way to join in the middle. Should be doable though.

**Comment by GlancingMind** [comment]
@MichaelMure I fiddled around with your PR on my own fork. I think I found the Problem with the WebUI.
The WebUI passes the CommentId (the TimelineId of type CombinedId) to the Target of the EditCommentMutation.
This Id was then passed wrongly around. Instead the Resolver has to extract the OperationId of the CommentId and pass this OpId around. I fixed this and now the WebUI fails with the same error as the TermUI.

One problem left, the extracted OpId is only a Prefix and will fail the id validation due to "invalid length"... :'(

**Comment by GlancingMind** [comment]
Got it! Editing of comments via CLI, TermUI and WebUI work again. https://github.com/GlancingMind/git-bug/pull/57
Unfortunately the fix looks rather bad... duplicating the same code in three different places scream for a better solution.
I could remove the redundant code by placing it into EditCommentOperation::Apply, but then the EditCommentOperationTarget 
must be a CombinedId. Making the Target a TimelineItem rather than an Operation.

Side Note: Is the separation of a TimelineItem and an Operation needed or could an Operation not be a TimelineItem?

**Comment by MichaelMure** [comment]
https://github.com/MichaelMure/git-bug/pull/835 brought to light the bug that likely cause this. Somewhere in the code an EditCommentOperation was created, the Id() was taken to register the change in the timeline, then metadata were added to that operation, changing the data and the Id. A newly created assertion failed in that branch, fix pending.
