### ISSUE TITLE
feat: delete a bug locally

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#66]
Todo:

`git bug rm <id> [<remote>]`: remove a bug locally or on a remote

Notes: this will require a way to pull only partially the bugs (for instance, only bug active in the last year).

**Comment by sladyn98** [comment]
Deleting a bug locally could be a fairly easy task by removing it from the ```tree``` and the `cache`, one possible barrier could be the timestamp, does the ```func (b BugsByCreationTime)``` return a bug instance? because that would make things much more easier in terms of implementation.

**Comment by pawamoy** [comment]
So there is currently no way to delete a bug locally? Like the one I just created, called "Test", with nothing in it?

**Comment by sladyn98** [comment]
No actually there is no way apart from going to `git` file and deleting it. We are working on developing this feature.

**Comment by pawamoy** [comment]
Okay, thanks, here's how I've done it:

```bash
rm .git/git-bug/bug-cache
rm .git/refs/bugs/BUG_ID
```
...where `BUG_ID` is of course the identifier of the bug (type the first few letters then autocomplete).

**Comment by sladyn98** [comment]
Yeah that is wonderful. If you need any help fell free to ask.

**Comment by sladyn98** [comment]
@MichaelMure I was trying to work on deleting a bug locally. According to me a bug needs to be delted from three different components of our software:
1) The Bug cache...
2) The local refs folder
3) The Bug Excerpt Cache(I guess this populates itself from point 1)
So The way I thought of appraching this would be create a function to remove an entry from the caches and one function to remove the same from the corresponding local refs folder.
Is this apporach correct or do you have different views?

**Comment by MichaelMure** [comment]
Done! Thanks @Invincibot
