### ISSUE TITLE
bridge pull gives: rofi.current/build$ git bug bridge pull panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by DaveDavenport** [MichaelMure/git-bug#686]
After an initial pull (that worked) I made an online change (closed bug) and did another bridge pull, this returned the following trace:

```
panic: runtime error: index out of range [0] with length 0

goroutine 42 [running]:
github.com/MichaelMure/git-bug/bridge/github.(*iterator).NextTimelineItem(0xc000246140, 0xc000130d00)
	/home/michael/dev/git-bug/bridge/github/iterator.go:252 +0x405
github.com/MichaelMure/git-bug/bridge/github.(*githubImporter).ImportAll.func1(0xc0003cc1e0, 0xc000130d80, 0xc00011d140)
	/home/michael/dev/git-bug/bridge/github/import.go:75 +0x8a
created by github.com/MichaelMure/git-bug/bridge/github.(*githubImporter).ImportAll
	/home/michael/dev/git-bug/bridge/github/import.go:60 +0x1bf
```

Version:
```
$git bug --version
git-bug version v0.7.2
```

Please let me know if you need more information.

**Comment by MichaelMure** [comment]
Could you try to reproduce after compiling from master? There has been significant (unreleased) changes in the github bridge.

**Comment by DaveDavenport** [comment]
sorry, I did a

 `go get -u ./ ...`

still get a compile error:

```
go generate
../../../go/src/github.com/blevesearch/bleve/index/scorch/segment_plugin.go:24:2: cannot find package "github.com/blevesearch/zapx/v11" in any of:
```

What do I need to do to build it? (sorry go noob)

**Comment by GlancingMind** [comment]
> sorry, I did a
> 
> `go get -u ./ ...`
> 
> still get a compile error:
> 
> ```
> go generate
> ../../../go/src/github.com/blevesearch/bleve/index/scorch/segment_plugin.go:24:2: cannot find package "github.com/blevesearch/zapx/v11" in any of:
> ```
> 
> What do I need to do to build it? (sorry go noob)

Hi Dave,

I tried to reproduce your error, but I failed. In my case, `go get -u ./ ...` is finishing successfully as well as `go generate`. :(
Just in case, did you try to compile git-bug via the provided Makefile? Calling `make` should be sufficient to download all dependencies and compile the git-bug binary. At least, works like this on my machine :grin:.

If compilation still fails, don't hesitate to report back.

**Comment by DaveDavenport** [comment]
make failed for me:
```
git-bug$ make
go generate
../../../go/src/github.com/blevesearch/bleve/index/scorch/segment_plugin.go:24:2: cannot find package "github.com/blevesearch/zapx/v11" in any of:
	/usr/lib/go-1.10/src/github.com/blevesearch/zapx/v11 (from $GOROOT)
```

I am on an old ubuntu version on this laptop (work laptop).
I can try it with a more up2date one later.

**Comment by DaveDavenport** [comment]
yes, on 20.04 make actually fetches stuff.  I will report back once tested.

**Comment by DaveDavenport** [comment]
Yes, 663c429605b66d1947d0b7cc50a11cd142494bb2 works.
I tried creating closing/opening/closing and more and this now works fine.

Thanks!.
