### ISSUE TITLE
Feature: Kanban support

### ISSUE THREAD

**Issue by 0xAlcibiades** [MichaelMure/git-bug#717]
Is there a desire for a kanban view in either the termui or web ui for distributed project management?

**Comment by GlancingMind** [comment]
Just for reference https://github.com/MichaelMure/git-bug/issues/637

**Comment by MichaelMure** [comment]
This is being worked on in https://github.com/MichaelMure/git-bug/pull/843

**Comment by MichaelMure** [comment]
Closing as duplicate of #637
