### ISSUE TITLE
Github Bridge - Auto Token - "404 error"

### ISSUE THREAD

**Issue by gavin-shaw** [MichaelMure/git-bug#720]
Follow the `git bug bridge configure` wizard as per below. Check the error at the end. A breaking change at github?

```
git bug bridge configure
1]: github
[2]: gitlab
[3]: jira
[4]: launchpad-preview
target: 1
name [default]: 

Detected projects:
[1]: github.com/my-user/private-project

[0]: Another project

Select option: 1
Github login: my-user

[1]: enter my token
[2]: interactive token creation

Select option: 2

git-bug will now generate an access token in your Github profile. Your credential are not stored and are only used to generate the token. The token is stored in the global git config.

The access scope depend on the type of repository.
Public:
  - 'public_repo': to be able to read public repositories
Private:
  - 'repo'       : to be able to read private repositories

[1]: public
[2]: private
repository visibility: 2

Password: 
Error: error creating token 404: {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
```

**Comment by mohe2015** [comment]
For me using the latest version in `master` and using "interactive token creation" worked.

**Comment by gavin-shaw** [comment]
Confirmed, thank you @mohe2015 . I think we should leave this open for others until master hits the package managers?

I am on mac with brew.

For those landing here, check the [releases](https://github.com/MichaelMure/git-bug/releases) page first to see if there is a release after 2021-11-28. If not, follow instructions under Installation > Compile from git (unstable) in the README.md.

```
git clone git@github.com:MichaelMure/git-bug.git
make install
export PATH=$PATH:$(go env GOROOT)/bin:$(go env GOPATH)/bin
```

Tested and working on Mac M1. Make sure you have latest version of go installed.

**Comment by MichaelMure** [comment]
Closing as it seems to be resolved. v0.8.0 has been released.
