### ISSUE TITLE
[question] How to import issues from GitHub and export them to GitLab?

### ISSUE THREAD

**Issue by mohe2015** [MichaelMure/git-bug#724]
I can't get this to work with the current `master` branch. The `git bug bridge push gitlab` always says `exported 0 issues with gitlab bridge`. I suspect it has something to do with the identites/users.
`git bug user` shows:
```
git bug user
Id: the-hash
Name: Moritz Hedtke
Email: Moritz.Hedtke@t-online.de
Login: 
Last modification: Sun Nov 28 15:13:26 2021 +2800
Last moditication (lamport):
Metadata:
    github-login --> mohe2015
    gitlab-login --> moritz.hedtke
```
(The information is my own)

**Comment by hoijui** [comment]
I have the same issue .. how did you solve it, @mohe2015 ?

**Comment by mohe2015** [comment]
I don't know any more unfortunately. Probably not at all

**Comment by mohe2015** [comment]
Maybe I used the git version and not the released version
