### ISSUE TITLE
import error: Something went wrong while executing your query. Please include `BDCC:213B:6AF4A8:6D1E7A:61FD9C2C` when reporting this issue.

### ISSUE THREAD

**Issue by a-m-joseph** [MichaelMure/git-bug#740]
Hi, when attempting to "git bug pull" from https://github.com/nixos/nixpkgs using the github bridge, I get:

`import error: Something went wrong while executing your query. Please include `BDCC:213B:6AF4A8:6D1E7A:61FD9C2C` when reporting this issue.`

**Comment by MichaelMure** [comment]
This was a problem on Github side, they had some trouble at that time. If you try again if should work.

**Comment by a-m-joseph** [comment]
It is still happening.  I can't seem to reopen this issue so I will file a new one.
