### ISSUE TITLE
When using custom --work-tree identity is not found

### ISSUE THREAD

**Issue by tionis** [MichaelMure/git-bug#834]
I'm using a custom git dir and working tree and am creating an identity using
```sh
git --git-dir=$HOME/.cosmo --work-tree=$HOME bug user create
```
When I only specify the `--git-dir` it works as expected to add bugs, but when using `--work-tree` it complains about the identity not existing.
This may be somewhat related #178, but I'm not exactly sure how work-tree is handled in git internally

**Comment by MichaelMure** [comment]
Upstream issue: https://github.com/go-git/go-git/issues/414

Closing as there is nothing I can do about it until it's fixed there.
