### ISSUE TITLE
`git bug bridge configure` interactive mode rejects gitlab token

### ISSUE THREAD

**Issue by yuriizinets** [MichaelMure/git-bug#838]
If token provided with `--token=...` arg, everything works, but interactive mode rejects it with "incorrect token format" message.

**Comment by MichaelMure** [comment]
Which version of git-bug are you using?

**Comment by yuriizinets** [comment]
Sorry for missing information.
Latest available with `brew install`.

```
$ git bug --version
git-bug version v0.7.2
```

**Comment by MichaelMure** [comment]
Could you try the master branch? There has been significant changes since that.

**Comment by yuriizinets** [comment]
Thanks for advice!
Is there any particular reason of avoiding new release?

**Comment by MichaelMure** [comment]
Well, I got myself thinking that the next version will be 1.0, which comes with some form of guarantee regarding the stored data. But there is still some things to achieve before that, but I'm starting to feel that a new release before that wouldn't hurt.

**Comment by MichaelMure** [comment]
FYI, if master doesn't solve your issue, it might be that gitlab changed its token format. In that case, that should be an easy fix: https://github.com/MichaelMure/git-bug/blob/master/bridge/gitlab/config.go#L203
