### ISSUE TITLE
`git bug pull` fails with panic: DFS failed

### ISSUE THREAD

**Issue by weatherhead99** [MichaelMure/git-bug#845]
First of all thanks for your excellent software.

when doing a `git bug pull` on an already established repository, but which has not been checked out on this machine before, with the latest master (cd528724), I get the following error:

```

Fetching remote ...
already up-to-datealready up-to-date
Merging data ...
panic: DFS failed

goroutine 77 [running]:
github.com/MichaelMure/git-bug/entity/dag.read({{0x1185c0c, 0x3}, {0x11863aa, 0x4}, 0x12391d8, 0x4}, {0x136fba0, 0xc000400420}, {0x1356e40, 0xc0005302d0}, ...)
        /home/danw/Software/git-bug/entity/dag/entity.go:164 +0xf90
github.com/MichaelMure/git-bug/entity/dag.merge({{0x1185c0c, 0x3}, {0x11863aa, 0x4}, 0x12391d8, 0x4}, {0x136fba0?, 0xc000400420}, {0x1356e40, 0xc0005302d0}, ...)
        /home/danw/Software/git-bug/entity/dag/entity_actions.go:101 +0x185
github.com/MichaelMure/git-bug/entity/dag.MergeAll.func1()
        /home/danw/Software/git-bug/entity/dag/entity_actions.go:85 +0x2cf
created by github.com/MichaelMure/git-bug/entity/dag.MergeAll
        /home/danw/Software/git-bug/entity/dag/entity_actions.go:74 +0x1a5

```

this does seem to be an issue with this specific repo, and it's not a problem for me to reset it and re-import all the issues from gitlab. But I couldn't find out how to safely do that.

**Comment by MichaelMure** [comment]
Any idea when you created that original repo? There is a good chance that's data created when I was still working on the data model, before everything got stabilized properly.

**Comment by weatherhead99** [comment]
yeah, quite a while ago. Though I tried the various upgrade scripts etc and couldn't get anything to work. I don't really need to retain the bug data but is there any way to remove all git-bug data so I can start again?

**Comment by MichaelMure** [comment]
I suppose the migration tool is stuck the same way as it can't read the data coming from that WIP git-bug.

You can delete everything and start over by deleting `.git/git-bug` and running the following commands to remove bugs  and identities (from https://github.com/MichaelMure/git-bug/blob/master/Makefile):
```
git for-each-ref refs/identities/ | cut -f 2 | $(XARGS) -n 1 git update-ref -d
git for-each-ref refs/remotes/origin/identities/ | cut -f 2 | $(XARGS) -n 1 git update-ref -d
git for-each-ref refs/bugs/ | cut -f 2 | $(XARGS) -n 1 git update-ref -d
git for-each-ref refs/remotes/origin/bugs/ | cut -f 2 | $(XARGS) -n 1 git update-ref -d
```
