### ISSUE TITLE
Enhance `ls-id` (or merge functionality into `ls`)

### ISSUE THREAD

**Issue by smoyer64** [MichaelMure/git-bug#863]
As noted in https://github.com/MichaelMure/git-bug/pull/842#issuecomment-1213194755, `ls-id` doesn't have the querying/filtering abilities of `ls` but does provide the ability to list only bug hash prefixes (ids).  Now that https://github.com/MichaelMure/git-bug/pull/851 is merged, it's possible to use `ls` for this purpose (on *nix) as follows:

```shell
git bug ls  [QUERY] [flags] | cut -f1
```

**Comment by MichaelMure** [comment]
Reflecting a bit on this, it make sense to have a `ls` formatter spewing only IDs, it avoids the need to do pipe handling, and it's a kinda more natural concept: "just format ls the way you want", rather than polluting the entity namespace.

Not a fan of -f quiet though, let's call it -f id.

**Comment by smoyer64** [comment]
Seems like part of my CLI duties ;) ... I could take care of this on Monday (8/29).

**Comment by MichaelMure** [comment]
Cobra has a deprecation feature on commands, we can use that to keep it around for some time.
