### ISSUE TITLE
version information is not set with `go install`

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#928]
Due to those information being set through the makefile (https://github.com/MichaelMure/git-bug/blob/master/Makefile#L3-L5), installing git-bug with `go install` result in `version` returning empty version data:
```
$ git bug version
git-bug version: -dev-
```

We should consider moving to the golang built-in feature: https://blog.carlmjohnson.net/post/2021/golang-118-minor-features/#1-version-control-information-included-in-the-binary

**Comment by vasser** [comment]
Hi @MichaelMure, I've prepared a fix for this issue, but I can't push since do not have correct access rights 👀 
Is there anything on my side that should be fixed?

**Comment by vasser** [comment]
Thank you for explanation. I can open a PR with contribution file as a separate PR if you do not mind
