### ISSUE TITLE
add some documentation on how it behaves with git-log

### ISSUE THREAD

**Issue by guilbep** [MichaelMure/git-bug#930]
I'm a user of the `git log --all --decorate --oneline --graph` and I was surprised to see the commits used by git-bug appearing under the author ' <>'.

1. It is not mentioned in the documentation that it will be the case
2. Maybe it's because of something I did? Is the author always ' <>' ? Is there any reason ?
3. It's easy to hide them with the following command `git log --all --decorate --oneline --graph  --perl-regexp --author='^((?! <>).*)$'`
4. Maybe we should add some information about this in the documentation.

I'd be glad to write a pull request, but I'm not sure where to document this or even if it's necessary. But I thought it was missing.

**Comment by MichaelMure** [comment]
Hmmm, git-bug put his data into `refs/bugs/*` or `refs/identities/*`, which are normally ignored by git commands. The problem is that you explicitly ask to show them with `--all`. Is that really necessary?

The author is not set in those commits because it's not meant for human consumption and therefore unnecessary. The actual author that git-bug use is set in the JSON stored in the git Blob.

**Comment by guilbep** [comment]
Ow, I could use `git log --decorate --oneline --graph --exclude="refs/bugs/*" --exclude="refs/identities/*" --all` . then :) It's better.
- I like to use the `--all` options. It allows me to see all refs (branches, tags) that sometimes don't show (https://stackoverflow.com/a/70134496)
- Ok perfect! 

Maybe that's not necessary to add this information in the documentation then. Thank you

**Comment by MichaelMure** [comment]
Just FYI, there is going to be more of those namespaces in the future: boards, prs, config ...

**Comment by guilbep** [comment]
@MichaelMure Thank you for the information. What do you think of adding the namespaces in /doc/model.md at least then ? 👍

**Comment by MichaelMure** [comment]
I'd think that the people caring about this would find this issue instead.
