### ISSUE TITLE
WebUI needs to be migrated to use the Timeline

### ISSUE THREAD

**Issue by muggenhor** [MichaelMure/git-bug#94]
After editing the first comment (aka description) of an issue `git bug show $ID` correctly shows the latest version of that comment.

The WebUI however, only shows the first version of that comment.

**Comment by muggenhor** [comment]
> That said, if you refresh the webUI, you get the edited message, right ?

No. My reproduction scenario (on bb0066344a12d6ba58ab4dfc420b4fe5308e0a71, with Go 1.10) is this:

In the termui:
1. create a bug with some (non-empty) description
2. edit the description to something recognizably different
3. close termui and open the bug in the webui
4. expectation: new bug description, reality: see old bug description

**Comment by MichaelMure** [comment]
Hoo, yes indeed, I got confused. The `EditCommentOperation` correctly amend the message in both `Snapshot.Comments` (see https://github.com/MichaelMure/git-bug/blob/master/bug/op_edit_comment.go#L71-L72) and in the Timeline, but as I explained, the webUI use the raw array of `Operation` so it wont get the updated message.

**Comment by MichaelMure** [comment]
This has been dealt with in #104 but yet to be merged.
