### ISSUE TITLE
Some commands don't work as described in the Readme

### ISSUE THREAD

**Issue by ulrichard** [MichaelMure/git-bug#951]
For example
`git bug bridge configure`
results in
`Error: unknown command "configure" for "git-bug bridge"`
but the following command works:
`git bug bridge new`

For new users it would be beneficial if the Readme reflected the current state of the code.

**Comment by MichaelMure** [comment]
This is normal, as I just merged a very large rework of the CLI: https://github.com/MichaelMure/git-bug/pull/870

The readme will stay like that until the next released version.
