### ISSUE TITLE
Error: HTTP error 401 retrieving repository node id

### ISSUE THREAD

**Issue by jarbus** [MichaelMure/git-bug#958]
Just re-set up a github bridge after it stopped working, and am trying to push changes. I can successfully reconfigure the bridge, and I have existing git-bug issues, but I can't push. When I do, I get the following errors:

```
$ git bug bridge push
Error: HTTP error 401 retrieving repository node id
```

and running `git bug bridge pull` hangs indefinitely

**Comment by MichaelMure** [comment]
That means that the token being used for auth is invalid. Would it be possible it expired? How did you set it up?

**Comment by jarbus** [comment]
I've tried manually creating a token and doing the interactive way when setting up a new bridge. I was able to create a token both times that seemed valid, github successfully added the token both times and gave the menu to allow git bug permissions.

**Comment by MichaelMure** [comment]
Just to confirm, if you setup a new bridge, go through the interactive setup up to completion, and try to pull you get that 401?

Could it be that you try to access a private repo with a token you setup for only public ones?

**Comment by jarbus** [comment]
I deleted all my previous tokens, and tried creating a new token interactively. This seems to have fixed the issue. I'm not sure what was causing it, but it might be that it was using an expired token.
