### ISSUE TITLE
Students, would you like to work on git-bug as part of a google Summer of Code ?

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/git-bug#96]
git-bug will most likely get a slot in the [Google Summer of Code program](https://summerofcode.withgoogle.com/) through the [Coala organisation](https://coala.io).

Would you like to be this student ?

At this point, project ideas are:
- a Github exporter (https://github.com/MichaelMure/git-bug/issues/56)
- an importer/exporter for Gitlab / Launchpad / your favorite bug tracker
- improving the webUI to make it matche the features of the terminal UI 
- adding more features in git-bug in general (see https://github.com/MichaelMure/git-bug/issues)
- any project you would like to take care of

To get your footing in the git-bug project, there is a bunch of simple issues you could get started with:
- in general, issues marked as `Easy pick` (https://github.com/MichaelMure/git-bug/issues?q=is%3Aissue+is%3Aopen+label%3A%22Easy+pick%22)
- MichaelMure/git-bug#93
- MichaelMure/git-bug#94
- MichaelMure/git-bug#47
- MichaelMure/git-bug#74

Also, make sure to read and understand the [technical documentation](https://github.com/MichaelMure/git-bug/tree/master/doc).

Related issue: https://github.com/coala/projects/issues/648

**Comment by Anmolbansal1** [comment]
@MichaelMure yes, I am interested in working on git-bug and currently exploring its codebase and would like to start on contributing on some issues

**Comment by sladyn98** [comment]
@MichaelMure yeah I am interested in working on git-bug on maybe a bot - integration where we the user could interact with a bot in coala's case corobo like bot on a err-bot like backend. As @jayvdb suggested the bot would then put tokens in gitbug and gitbug would export it.In my opinion an exporter would solve most of the use case.

**Comment by MichaelMure** [comment]
@A-Hilaly will be this student !
