### ISSUE TITLE
Submodules and working trees are not handled correctly

### ISSUE THREAD

**Issue by tionis** [MichaelMure/git-bug#971]
In git submodules and working trees the .git path is a file linking to the real working tree via following syntax:
```
gitdir: /some/absolute/or/relative/path
```
This is not handled correctly and throws a `Error: .git exist but is not a directory` error

**Comment by MichaelMure** [comment]
What would you expect to happen in that case? Read that file and open the corresponding repo?

In that case it could be an easy fix over there: https://github.com/MichaelMure/git-bug/blob/f94616ec76e01145a7b2b90c11b27a25d4a4be96/repository/gogit.go#L174

**Comment by tionis** [comment]
Yes, that would be the same behavior as git.

**Comment by tionis** [comment]
As far as I have seen, the paths in these files don't recurse. Instead, nested submodules/working trees point to the top most "real" git dir.
I think a simple parsing of the .git file and a change-dir should suffice

**Comment by DarthRubik** [comment]
I have a WIP solution for this that I will post probably tonight after I clean
it up

**Comment by DarthRubik** [comment]
Oh....Oops...I did not notice that a solution for this was already posted

**Comment by tionis** [comment]
This seems to be fixed
