### ISSUE TITLE
GoKart scanning is panicking

### ISSUE THREAD

**Issue by smoyer64** [MichaelMure/git-bug#972]
I've created a PR to fix the issue in GoKart (https://github.com/praetorian-inc/gokart/pull/84) along with the associated issue (https://github.com/praetorian-inc/gokart/issues/83) containing the stack trace.

While I was working on GoKart I also took care of upgrading it to better scan generics which should be helpful.  I'll try to figure out a way to build the project from an alternate repository (my fork) which is hampered by `go install` constraints.

**Comment by MichaelMure** [comment]
Neat!

> I'll try to figure out a way to build the project from an alternate repository (my fork) which is hampered by go install constraints.

Maybe just wait a bit to see if upstream merge your PR? Otherwise I think you'd need to git clone and compile, which is a bit cumbersome.

**Comment by smoyer64** [comment]
Yeah ... I just know this project can be slow (but I think maybe a panic will get faster attention.  If neither happens this week, I'll put a PR in `git-bug` to turn off GoKart scanning temporarily and a tracking issue to re-enable it later.  Next I'm going to see about the periodic security scanning (which will also be impacted by the panic).
